/*
 * generated by Xtext
 */
package org.w3.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.w3.ui.internal.Xpath20Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Xpath20ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Xpath20Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Xpath20Activator.getInstance().getInjector(Xpath20Activator.ORG_W3_XPATH20);
	}
	
}
