/**
 * generated by Xtext
 */
package org.w3.validation;

import org.w3.validation.AbstractXpath20Validator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class Xpath20Validator extends AbstractXpath20Validator {
}
