/*
* generated by Xtext
*/
package org.w3.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.w3.services.Xpath20GrammarAccess;

public class Xpath20Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Xpath20GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_COMMENT");
	}
	
	@Override
	protected org.w3.parser.antlr.internal.InternalXpath20Parser createParser(XtextTokenStream stream) {
		return new org.w3.parser.antlr.internal.InternalXpath20Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XPath";
	}
	
	public Xpath20GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Xpath20GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
