/*
 * generated by Xtext
 */
package org.w3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Xpath20UiModule extends org.w3.ui.AbstractXpath20UiModule {
	public Xpath20UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
