<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_0" nsURI="http://release.niem.gov/niem/codes/occs_facility/3.0/"
    nsPrefix="_0">
  <eAnnotations source="http://release.niem.gov/niem/conformanceTargets/3.0/">
    <details key="conformanceTargets" value="http://reference.niem.gov/niem/specification/naming-and-design-rules/3.0/#ReferenceSchemaDocument"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="FacilityUsageCodeSimpleType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_11110000" literal="11-11 00 00"/>
    <eLiterals name="_11111100" value="1" literal="11-11 11 00"/>
    <eLiterals name="_11111111" value="2" literal="11-11 11 11"/>
    <eLiterals name="_11111117" value="3" literal="11-11 11 17"/>
    <eLiterals name="_11111400" value="4" literal="11-11 14 00"/>
    <eLiterals name="_11111411" value="5" literal="11-11 14 11"/>
    <eLiterals name="_11111414" value="6" literal="11-11 14 14"/>
    <eLiterals name="_11112100" value="7" literal="11-11 21 00"/>
    <eLiterals name="_11112111" value="8" literal="11-11 21 11"/>
    <eLiterals name="_11112117" value="9" literal="11-11 21 17"/>
    <eLiterals name="_1111211711" value="10" literal="11-11 21 17 11"/>
    <eLiterals name="_1111211714" value="11" literal="11-11 21 17 14"/>
    <eLiterals name="_11112121" value="12" literal="11-11 21 21"/>
    <eLiterals name="_11112122" value="13" literal="11-11 21 22"/>
    <eLiterals name="_11112123" value="14" literal="11-11 21 23"/>
    <eLiterals name="_11112124" value="15" literal="11-11 21 24"/>
    <eLiterals name="_1111212411" value="16" literal="11-11 21 24 11"/>
    <eLiterals name="_1111212414" value="17" literal="11-11 21 24 14"/>
    <eLiterals name="_1111212417" value="18" literal="11-11 21 24 17"/>
    <eLiterals name="_11112127" value="19" literal="11-11 21 27"/>
    <eLiterals name="_11120000" value="20" literal="11-12 00 00"/>
    <eLiterals name="_11121100" value="21" literal="11-12 11 00"/>
    <eLiterals name="_11121111" value="22" literal="11-12 11 11"/>
    <eLiterals name="_11121114" value="23" literal="11-12 11 14"/>
    <eLiterals name="_11122100" value="24" literal="11-12 21 00"/>
    <eLiterals name="_11122111" value="25" literal="11-12 21 11"/>
    <eLiterals name="_11122114" value="26" literal="11-12 21 14"/>
    <eLiterals name="_11122121" value="27" literal="11-12 21 21"/>
    <eLiterals name="_11122131" value="28" literal="11-12 21 31"/>
    <eLiterals name="_11122400" value="29" literal="11-12 24 00"/>
    <eLiterals name="_11122411" value="30" literal="11-12 24 11"/>
    <eLiterals name="_11122413" value="31" literal="11-12 24 13"/>
    <eLiterals name="_11122414" value="32" literal="11-12 24 14"/>
    <eLiterals name="_11122417" value="33" literal="11-12 24 17"/>
    <eLiterals name="_11122421" value="34" literal="11-12 24 21"/>
    <eLiterals name="_11122424" value="35" literal="11-12 24 24"/>
    <eLiterals name="_11122427" value="36" literal="11-12 24 27"/>
    <eLiterals name="_11122431" value="37" literal="11-12 24 31"/>
    <eLiterals name="_11122434" value="38" literal="11-12 24 34"/>
    <eLiterals name="_11122900" value="39" literal="11-12 29 00"/>
    <eLiterals name="_11122911" value="40" literal="11-12 29 11"/>
    <eLiterals name="_11122914" value="41" literal="11-12 29 14"/>
    <eLiterals name="_11122917" value="42" literal="11-12 29 17"/>
    <eLiterals name="_11122921" value="43" literal="11-12 29 21"/>
    <eLiterals name="_11130000" value="44" literal="11-13 00 00"/>
    <eLiterals name="_11131100" value="45" literal="11-13 11 00"/>
    <eLiterals name="_11131111" value="46" literal="11-13 11 11"/>
    <eLiterals name="_11131114" value="47" literal="11-13 11 14"/>
    <eLiterals name="_11131117" value="48" literal="11-13 11 17"/>
    <eLiterals name="_11131121" value="49" literal="11-13 11 21"/>
    <eLiterals name="_11131123" value="50" literal="11-13 11 23"/>
    <eLiterals name="_1113112311" value="51" literal="11-13 11 23 11"/>
    <eLiterals name="_1113112314" value="52" literal="11-13 11 23 14"/>
    <eLiterals name="_11131124" value="53" literal="11-13 11 24"/>
    <eLiterals name="_1113112411" value="54" literal="11-13 11 24 11"/>
    <eLiterals name="_1113112414" value="55" literal="11-13 11 24 14"/>
    <eLiterals name="_1113112417" value="56" literal="11-13 11 24 17"/>
    <eLiterals name="_11131127" value="57" literal="11-13 11 27"/>
    <eLiterals name="_11131131" value="58" literal="11-13 11 31"/>
    <eLiterals name="_11131133" value="59" literal="11-13 11 33"/>
    <eLiterals name="_1113113311" value="60" literal="11-13 11 33 11"/>
    <eLiterals name="_1113113314" value="61" literal="11-13 11 33 14"/>
    <eLiterals name="_1113113317" value="62" literal="11-13 11 33 17"/>
    <eLiterals name="_1113113321" value="63" literal="11-13 11 33 21"/>
    <eLiterals name="_11131134" value="64" literal="11-13 11 34"/>
    <eLiterals name="_11131137" value="65" literal="11-13 11 37"/>
    <eLiterals name="_11132100" value="66" literal="11-13 21 00"/>
    <eLiterals name="_1113211101" value="67" literal="11-13 21 11 01"/>
    <eLiterals name="_11132112" value="68" literal="11-13 21 12"/>
    <eLiterals name="_11132114" value="69" literal="11-13 21 14"/>
    <eLiterals name="_11132117" value="70" literal="11-13 21 17"/>
    <eLiterals name="_11132121" value="71" literal="11-13 21 21"/>
    <eLiterals name="_11132124" value="72" literal="11-13 21 24"/>
    <eLiterals name="_11132127" value="73" literal="11-13 21 27"/>
    <eLiterals name="_11132131" value="74" literal="11-13 21 31"/>
    <eLiterals name="_11132134" value="75" literal="11-13 21 34"/>
    <eLiterals name="_11132137" value="76" literal="11-13 21 37"/>
    <eLiterals name="_11132141" value="77" literal="11-13 21 41"/>
    <eLiterals name="_11132144" value="78" literal="11-13 21 44"/>
    <eLiterals name="_11132147" value="79" literal="11-13 21 47"/>
    <eLiterals name="_11132151" value="80" literal="11-13 21 51"/>
    <eLiterals name="_11132154" value="81" literal="11-13 21 54"/>
    <eLiterals name="_11132157" value="82" literal="11-13 21 57"/>
    <eLiterals name="_11132161" value="83" literal="11-13 21 61"/>
    <eLiterals name="_11132164" value="84" literal="11-13 21 64"/>
    <eLiterals name="_11132167" value="85" literal="11-13 21 67"/>
    <eLiterals name="_11132171" value="86" literal="11-13 21 71"/>
    <eLiterals name="_11132174" value="87" literal="11-13 21 74"/>
    <eLiterals name="_11132177" value="88" literal="11-13 21 77"/>
    <eLiterals name="_1113217711" value="89" literal="11-13 21 77 11"/>
    <eLiterals name="_1113217714" value="90" literal="11-13 21 77 14"/>
    <eLiterals name="_1113217717" value="91" literal="11-13 21 77 17"/>
    <eLiterals name="_1113217721" value="92" literal="11-13 21 77 21"/>
    <eLiterals name="_1113217724" value="93" literal="11-13 21 77 24"/>
    <eLiterals name="_11132700" value="94" literal="11-13 27 00"/>
    <eLiterals name="_11132711" value="95" literal="11-13 27 11"/>
    <eLiterals name="_11132714" value="96" literal="11-13 27 14"/>
    <eLiterals name="_11132717" value="97" literal="11-13 27 17"/>
    <eLiterals name="_11132721" value="98" literal="11-13 27 21"/>
    <eLiterals name="_11132723" value="99" literal="11-13 27 23"/>
    <eLiterals name="_11132726" value="100" literal="11-13 27 26"/>
    <eLiterals name="_11132900" value="101" literal="11-13 29 00"/>
    <eLiterals name="_11132911" value="102" literal="11-13 29 11"/>
    <eLiterals name="_11132914" value="103" literal="11-13 29 14"/>
    <eLiterals name="_11140000" value="104" literal="11-14 00 00"/>
    <eLiterals name="_11141500" value="105" literal="11-14 15 00"/>
    <eLiterals name="_11142100" value="106" literal="11-14 21 00"/>
    <eLiterals name="_11142111" value="107" literal="11-14 21 11"/>
    <eLiterals name="_11142114" value="108" literal="11-14 21 14"/>
    <eLiterals name="_11142117" value="109" literal="11-14 21 17"/>
    <eLiterals name="_11142121" value="110" literal="11-14 21 21"/>
    <eLiterals name="_11142124" value="111" literal="11-14 21 24"/>
    <eLiterals name="_11142400" value="112" literal="11-14 24 00"/>
    <eLiterals name="_11142411" value="113" literal="11-14 24 11"/>
    <eLiterals name="_11142415" value="114" literal="11-14 24 15"/>
    <eLiterals name="_11142418" value="115" literal="11-14 24 18"/>
    <eLiterals name="_11142421" value="116" literal="11-14 24 21"/>
    <eLiterals name="_11142424" value="117" literal="11-14 24 24"/>
    <eLiterals name="_11150000" value="118" literal="11-15 00 00"/>
    <eLiterals name="_11151100" value="119" literal="11-15 11 00"/>
    <eLiterals name="_11151111" value="120" literal="11-15 11 11"/>
    <eLiterals name="_11151114" value="121" literal="11-15 11 14"/>
    <eLiterals name="_11151121" value="122" literal="11-15 11 21"/>
    <eLiterals name="_11151127" value="123" literal="11-15 11 27"/>
    <eLiterals name="_11151134" value="124" literal="11-15 11 34"/>
    <eLiterals name="_1115113411" value="125" literal="11-15 11 34 11"/>
    <eLiterals name="_1115113414" value="126" literal="11-15 11 34 14"/>
    <eLiterals name="_1115113417" value="127" literal="11-15 11 34 17"/>
    <eLiterals name="_11151136" value="128" literal="11-15 11 36"/>
    <eLiterals name="_1115113611" value="129" literal="11-15 11 36 11"/>
    <eLiterals name="_1115113615" value="130" literal="11-15 11 36 15"/>
    <eLiterals name="_1115113618" value="131" literal="11-15 11 36 18"/>
    <eLiterals name="_1115113621" value="132" literal="11-15 11 36 21"/>
    <eLiterals name="_11151139" value="133" literal="11-15 11 39"/>
    <eLiterals name="_11151141" value="134" literal="11-15 11 41"/>
    <eLiterals name="_1115114111" value="135" literal="11-15 11 41 11"/>
    <eLiterals name="_1115114114" value="136" literal="11-15 11 41 14"/>
    <eLiterals name="_1115114117" value="137" literal="11-15 11 41 17"/>
    <eLiterals name="_11151144" value="138" literal="11-15 11 44"/>
    <eLiterals name="_1115114411" value="139" literal="11-15 11 44 11"/>
    <eLiterals name="_1115114414" value="140" literal="11-15 11 44 14"/>
    <eLiterals name="_11151147" value="141" literal="11-15 11 47"/>
    <eLiterals name="_1115114711" value="142" literal="11-15 11 47 11"/>
    <eLiterals name="_1115114714" value="143" literal="11-15 11 47 14"/>
    <eLiterals name="_1115114717" value="144" literal="11-15 11 47 17"/>
    <eLiterals name="_1115114721" value="145" literal="11-15 11 47 21"/>
    <eLiterals name="_11151152" value="146" literal="11-15 11 52"/>
    <eLiterals name="_11151155" value="147" literal="11-15 11 55"/>
    <eLiterals name="_11151158" value="148" literal="11-15 11 58"/>
    <eLiterals name="_1115115811" value="149" literal="11-15 11 58 11"/>
    <eLiterals name="_1115115814" value="150" literal="11-15 11 58 14"/>
    <eLiterals name="_11151198" value="151" literal="11-15 11 98"/>
    <eLiterals name="_11152100" value="152" literal="11-15 21 00"/>
    <eLiterals name="_11152109" value="153" literal="11-15 21 09"/>
    <eLiterals name="_1115210911" value="154" literal="11-15 21 09 11"/>
    <eLiterals name="_1115210914" value="155" literal="11-15 21 09 14"/>
    <eLiterals name="_1115210917" value="156" literal="11-15 21 09 17"/>
    <eLiterals name="_11152111" value="157" literal="11-15 21 11"/>
    <eLiterals name="_1115211111" value="158" literal="11-15 21 11 11"/>
    <eLiterals name="_1115211114" value="159" literal="11-15 21 11 14"/>
    <eLiterals name="_11152114" value="160" literal="11-15 21 14"/>
    <eLiterals name="_11152121" value="161" literal="11-15 21 21"/>
    <eLiterals name="_1115212111" value="162" literal="11-15 21 21 11"/>
    <eLiterals name="_1115212114" value="163" literal="11-15 21 21 14"/>
    <eLiterals name="_1115212117" value="164" literal="11-15 21 21 17"/>
    <eLiterals name="_11152124" value="165" literal="11-15 21 24"/>
    <eLiterals name="_1115212411" value="166" literal="11-15 21 24 11"/>
    <eLiterals name="_1115212414" value="167" literal="11-15 21 24 14"/>
    <eLiterals name="_1115212417" value="168" literal="11-15 21 24 17"/>
    <eLiterals name="_11152128" value="169" literal="11-15 21 28"/>
    <eLiterals name="_11152131" value="170" literal="11-15 21 31"/>
    <eLiterals name="_1115213111" value="171" literal="11-15 21 31 11"/>
    <eLiterals name="_1115213114" value="172" literal="11-15 21 31 14"/>
    <eLiterals name="_1115213117" value="173" literal="11-15 21 31 17"/>
    <eLiterals name="_1115213121" value="174" literal="11-15 21 31 21"/>
    <eLiterals name="_11152137" value="175" literal="11-15 21 37"/>
    <eLiterals name="_1115213711" value="176" literal="11-15 21 37 11"/>
    <eLiterals name="_1115213714" value="177" literal="11-15 21 37 14"/>
    <eLiterals name="_1115213717" value="178" literal="11-15 21 37 17"/>
    <eLiterals name="_1115213721" value="179" literal="11-15 21 37 21"/>
    <eLiterals name="_11152198" value="180" literal="11-15 21 98"/>
    <eLiterals name="_11160000" value="181" literal="11-16 00 00"/>
    <eLiterals name="_11161100" value="182" literal="11-16 11 00"/>
    <eLiterals name="_11161111" value="183" literal="11-16 11 11"/>
    <eLiterals name="_11161114" value="184" literal="11-16 11 14"/>
    <eLiterals name="_11161117" value="185" literal="11-16 11 17"/>
    <eLiterals name="_11161500" value="186" literal="11-16 15 00"/>
    <eLiterals name="_11161511" value="187" literal="11-16 15 11"/>
    <eLiterals name="_11161513" value="188" literal="11-16 15 13"/>
    <eLiterals name="_11162100" value="189" literal="11-16 21 00"/>
    <eLiterals name="_11162111" value="190" literal="11-16 21 11"/>
    <eLiterals name="_11162114" value="191" literal="11-16 21 14"/>
    <eLiterals name="_11162117" value="192" literal="11-16 21 17"/>
    <eLiterals name="_11162121" value="193" literal="11-16 21 21"/>
    <eLiterals name="_11162125" value="194" literal="11-16 21 25"/>
    <eLiterals name="_11162129" value="195" literal="11-16 21 29"/>
    <eLiterals name="_11162700" value="196" literal="11-16 27 00"/>
    <eLiterals name="_11162711" value="197" literal="11-16 27 11"/>
    <eLiterals name="_11162714" value="198" literal="11-16 27 14"/>
    <eLiterals name="_11162718" value="199" literal="11-16 27 18"/>
    <eLiterals name="_11162722" value="200" literal="11-16 27 22"/>
    <eLiterals name="_11163100" value="201" literal="11-16 31 00"/>
    <eLiterals name="_11163114" value="202" literal="11-16 31 14"/>
    <eLiterals name="_11163117" value="203" literal="11-16 31 17"/>
    <eLiterals name="_11164200" value="204" literal="11-16 42 00"/>
    <eLiterals name="_11164211" value="205" literal="11-16 42 11"/>
    <eLiterals name="_11164214" value="206" literal="11-16 42 14"/>
    <eLiterals name="_11164217" value="207" literal="11-16 42 17"/>
    <eLiterals name="_11170000" value="208" literal="11-17 00 00"/>
    <eLiterals name="_11170500" value="209" literal="11-17 05 00"/>
    <eLiterals name="_11170700" value="210" literal="11-17 07 00"/>
    <eLiterals name="_11170900" value="211" literal="11-17 09 00"/>
    <eLiterals name="_11171100" value="212" literal="11-17 11 00"/>
    <eLiterals name="_11171111" value="213" literal="11-17 11 11"/>
    <eLiterals name="_11171113" value="214" literal="11-17 11 13"/>
    <eLiterals name="_11171300" value="215" literal="11-17 13 00"/>
    <eLiterals name="_11171500" value="216" literal="11-17 15 00"/>
    <eLiterals name="_11171700" value="217" literal="11-17 17 00"/>
    <eLiterals name="_11171900" value="218" literal="11-17 19 00"/>
    <eLiterals name="_11171911" value="219" literal="11-17 19 11"/>
    <eLiterals name="_11171913" value="220" literal="11-17 19 13"/>
    <eLiterals name="_11171915" value="221" literal="11-17 19 15"/>
    <eLiterals name="_11172100" value="222" literal="11-17 21 00"/>
    <eLiterals name="_11172111" value="223" literal="11-17 21 11"/>
    <eLiterals name="_11172114" value="224" literal="11-17 21 14"/>
    <eLiterals name="_11172117" value="225" literal="11-17 21 17"/>
    <eLiterals name="_11172121" value="226" literal="11-17 21 21"/>
    <eLiterals name="_11172500" value="227" literal="11-17 25 00"/>
    <eLiterals name="_11172511" value="228" literal="11-17 25 11"/>
    <eLiterals name="_11172514" value="229" literal="11-17 25 14"/>
    <eLiterals name="_11172517" value="230" literal="11-17 25 17"/>
    <eLiterals name="_11172700" value="231" literal="11-17 27 00"/>
    <eLiterals name="_11172711" value="232" literal="11-17 27 11"/>
    <eLiterals name="_11172714" value="233" literal="11-17 27 14"/>
    <eLiterals name="_11172717" value="234" literal="11-17 27 17"/>
    <eLiterals name="_11172720" value="235" literal="11-17 27 20"/>
    <eLiterals name="_11172723" value="236" literal="11-17 27 23"/>
    <eLiterals name="_11172726" value="237" literal="11-17 27 26"/>
    <eLiterals name="_11172729" value="238" literal="11-17 27 29"/>
    <eLiterals name="_11172732" value="239" literal="11-17 27 32"/>
    <eLiterals name="_11172735" value="240" literal="11-17 27 35"/>
    <eLiterals name="_11172738" value="241" literal="11-17 27 38"/>
    <eLiterals name="_11172741" value="242" literal="11-17 27 41"/>
    <eLiterals name="_11172744" value="243" literal="11-17 27 44"/>
    <eLiterals name="_11210000" value="244" literal="11-21 00 00"/>
    <eLiterals name="_11211200" value="245" literal="11-21 12 00"/>
    <eLiterals name="_11211211" value="246" literal="11-21 12 11"/>
    <eLiterals name="_11211215" value="247" literal="11-21 12 15"/>
    <eLiterals name="_11211219" value="248" literal="11-21 12 19"/>
    <eLiterals name="_11211223" value="249" literal="11-21 12 23"/>
    <eLiterals name="_11211227" value="250" literal="11-21 12 27"/>
    <eLiterals name="_11211231" value="251" literal="11-21 12 31"/>
    <eLiterals name="_11211500" value="252" literal="11-21 15 00"/>
    <eLiterals name="_11211511" value="253" literal="11-21 15 11"/>
    <eLiterals name="_11211515" value="254" literal="11-21 15 15"/>
    <eLiterals name="_11211519" value="255" literal="11-21 15 19"/>
    <eLiterals name="_11211523" value="256" literal="11-21 15 23"/>
    <eLiterals name="_11211527" value="257" literal="11-21 15 27"/>
    <eLiterals name="_11211531" value="258" literal="11-21 15 31"/>
    <eLiterals name="_11211535" value="259" literal="11-21 15 35"/>
    <eLiterals name="_11211539" value="260" literal="11-21 15 39"/>
    <eLiterals name="_11211543" value="261" literal="11-21 15 43"/>
    <eLiterals name="_11211547" value="262" literal="11-21 15 47"/>
    <eLiterals name="_11211700" value="263" literal="11-21 17 00"/>
    <eLiterals name="_11212200" value="264" literal="11-21 22 00"/>
    <eLiterals name="_11212211" value="265" literal="11-21 22 11"/>
    <eLiterals name="_11212215" value="266" literal="11-21 22 15"/>
    <eLiterals name="_11212500" value="267" literal="11-21 25 00"/>
    <eLiterals name="_11212511" value="268" literal="11-21 25 11"/>
    <eLiterals name="_11212515" value="269" literal="11-21 25 15"/>
    <eLiterals name="_11212519" value="270" literal="11-21 25 19"/>
    <eLiterals name="_11212800" value="271" literal="11-21 28 00"/>
    <eLiterals name="_11213200" value="272" literal="11-21 32 00"/>
    <eLiterals name="_11213211" value="273" literal="11-21 32 11"/>
    <eLiterals name="_11213215" value="274" literal="11-21 32 15"/>
    <eLiterals name="_11213500" value="275" literal="11-21 35 00"/>
    <eLiterals name="_11213800" value="276" literal="11-21 38 00"/>
    <eLiterals name="_11214200" value="277" literal="11-21 42 00"/>
    <eLiterals name="_11214500" value="278" literal="11-21 45 00"/>
    <eLiterals name="_11214800" value="279" literal="11-21 48 00"/>
    <eLiterals name="_11215200" value="280" literal="11-21 52 00"/>
    <eLiterals name="_11215500" value="281" literal="11-21 55 00"/>
    <eLiterals name="_11215511" value="282" literal="11-21 55 11"/>
    <eLiterals name="_11215515" value="283" literal="11-21 55 15"/>
    <eLiterals name="_11215519" value="284" literal="11-21 55 19"/>
    <eLiterals name="_11215523" value="285" literal="11-21 55 23"/>
    <eLiterals name="_11230000" value="286" literal="11-23 00 00"/>
    <eLiterals name="_11231200" value="287" literal="11-23 12 00"/>
    <eLiterals name="_11231211" value="288" literal="11-23 12 11"/>
    <eLiterals name="_11231215" value="289" literal="11-23 12 15"/>
    <eLiterals name="_11231219" value="290" literal="11-23 12 19"/>
    <eLiterals name="_11231223" value="291" literal="11-23 12 23"/>
    <eLiterals name="_11231227" value="292" literal="11-23 12 27"/>
    <eLiterals name="_11231231" value="293" literal="11-23 12 31"/>
    <eLiterals name="_11231235" value="294" literal="11-23 12 35"/>
    <eLiterals name="_11231243" value="295" literal="11-23 12 43"/>
    <eLiterals name="_11231247" value="296" literal="11-23 12 47"/>
    <eLiterals name="_11231500" value="297" literal="11-23 15 00"/>
    <eLiterals name="_11231800" value="298" literal="11-23 18 00"/>
    <eLiterals name="_11250000" value="299" literal="11-25 00 00"/>
    <eLiterals name="_11251200" value="300" literal="11-25 12 00"/>
    <eLiterals name="_11251211" value="301" literal="11-25 12 11"/>
    <eLiterals name="_11251215" value="302" literal="11-25 12 15"/>
    <eLiterals name="_11251219" value="303" literal="11-25 12 19"/>
    <eLiterals name="_11251223" value="304" literal="11-25 12 23"/>
    <eLiterals name="_11251227" value="305" literal="11-25 12 27"/>
    <eLiterals name="_11251239" value="306" literal="11-25 12 39"/>
    <eLiterals name="_11251243" value="307" literal="11-25 12 43"/>
    <eLiterals name="_11251247" value="308" literal="11-25 12 47"/>
    <eLiterals name="_11251251" value="309" literal="11-25 12 51"/>
    <eLiterals name="_11251255" value="310" literal="11-25 12 55"/>
    <eLiterals name="_11251259" value="311" literal="11-25 12 59"/>
    <eLiterals name="_11251263" value="312" literal="11-25 12 63"/>
    <eLiterals name="_11251267" value="313" literal="11-25 12 67"/>
    <eLiterals name="_11251271" value="314" literal="11-25 12 71"/>
    <eLiterals name="_11255500" value="315" literal="11-25 55 00"/>
    <eLiterals name="_11255512" value="316" literal="11-25 55 12"/>
    <eLiterals name="_11255515" value="317" literal="11-25 55 15"/>
    <eLiterals name="_11270000" value="318" literal="11-27 00 00"/>
    <eLiterals name="_11271200" value="319" literal="11-27 12 00"/>
    <eLiterals name="_11271211" value="320" literal="11-27 12 11"/>
    <eLiterals name="_11271215" value="321" literal="11-27 12 15"/>
    <eLiterals name="_11271500" value="322" literal="11-27 15 00"/>
    <eLiterals name="_11271511" value="323" literal="11-27 15 11"/>
    <eLiterals name="_11271515" value="324" literal="11-27 15 15"/>
    <eLiterals name="_11271800" value="325" literal="11-27 18 00"/>
    <eLiterals name="_11272200" value="326" literal="11-27 22 00"/>
    <eLiterals name="_11272211" value="327" literal="11-27 22 11"/>
    <eLiterals name="_11272500" value="328" literal="11-27 25 00"/>
    <eLiterals name="_11272511" value="329" literal="11-27 25 11"/>
    <eLiterals name="_11272515" value="330" literal="11-27 25 15"/>
    <eLiterals name="_11272519" value="331" literal="11-27 25 19"/>
    <eLiterals name="_11272523" value="332" literal="11-27 25 23"/>
    <eLiterals name="_11272527" value="333" literal="11-27 25 27"/>
    <eLiterals name="_11272800" value="334" literal="11-27 28 00"/>
    <eLiterals name="_11273200" value="335" literal="11-27 32 00"/>
    <eLiterals name="_11273500" value="336" literal="11-27 35 00"/>
    <eLiterals name="_11273800" value="337" literal="11-27 38 00"/>
    <eLiterals name="_11273811" value="338" literal="11-27 38 11"/>
    <eLiterals name="_11273814" value="339" literal="11-27 38 14"/>
    <eLiterals name="_11273817" value="340" literal="11-27 38 17"/>
    <eLiterals name="_11274200" value="341" literal="11-27 42 00"/>
    <eLiterals name="_11274500" value="342" literal="11-27 45 00"/>
    <eLiterals name="_11274800" value="343" literal="11-27 48 00"/>
    <eLiterals name="_11274811" value="344" literal="11-27 48 11"/>
    <eLiterals name="_11274815" value="345" literal="11-27 48 15"/>
    <eLiterals name="_11275200" value="346" literal="11-27 52 00"/>
    <eLiterals name="_11275500" value="347" literal="11-27 55 00"/>
    <eLiterals name="_11275511" value="348" literal="11-27 55 11"/>
    <eLiterals name="_11275515" value="349" literal="11-27 55 15"/>
    <eLiterals name="_11275519" value="350" literal="11-27 55 19"/>
    <eLiterals name="_11275521" value="351" literal="11-27 55 21"/>
    <eLiterals name="_11275522" value="352" literal="11-27 55 22"/>
    <eLiterals name="_11275523" value="353" literal="11-27 55 23"/>
    <eLiterals name="_11276541" value="354" literal="11-27 65 41"/>
    <eLiterals name="_11290000" value="355" literal="11-29 00 00"/>
    <eLiterals name="_11291200" value="356" literal="11-29 12 00"/>
    <eLiterals name="_11291211" value="357" literal="11-29 12 11"/>
    <eLiterals name="_1129121111" value="358" literal="11-29 12 11 11"/>
    <eLiterals name="_11291214" value="359" literal="11-29 12 14"/>
    <eLiterals name="_1129121414" value="360" literal="11-29 12 14 14"/>
    <eLiterals name="_1129121417" value="361" literal="11-29 12 14 17"/>
    <eLiterals name="_1129121420" value="362" literal="11-29 12 14 20"/>
    <eLiterals name="_1129121423" value="363" literal="11-29 12 14 23"/>
    <eLiterals name="_1129121433" value="364" literal="11-29 12 14 33"/>
    <eLiterals name="_11291218" value="365" literal="11-29 12 18"/>
    <eLiterals name="_1129121811" value="366" literal="11-29 12 18 11"/>
    <eLiterals name="_1129121815" value="367" literal="11-29 12 18 15"/>
    <eLiterals name="_1129121817" value="368" literal="11-29 12 18 17"/>
    <eLiterals name="_1129121819" value="369" literal="11-29 12 18 19"/>
    <eLiterals name="_1129121821" value="370" literal="11-29 12 18 21"/>
    <eLiterals name="_1129121827" value="371" literal="11-29 12 18 27"/>
    <eLiterals name="_1129121831" value="372" literal="11-29 12 18 31"/>
    <eLiterals name="_11291225" value="373" literal="11-29 12 25"/>
    <eLiterals name="_11292800" value="374" literal="11-29 28 00"/>
    <eLiterals name="_11292811" value="375" literal="11-29 28 11"/>
    <eLiterals name="_11292815" value="376" literal="11-29 28 15"/>
    <eLiterals name="_11292819" value="377" literal="11-29 28 19"/>
    <eLiterals name="_11292823" value="378" literal="11-29 28 23"/>
    <eLiterals name="_11292827" value="379" literal="11-29 28 27"/>
    <eLiterals name="_11292831" value="380" literal="11-29 28 31"/>
    <eLiterals name="_11292835" value="381" literal="11-29 28 35"/>
    <eLiterals name="_11292839" value="382" literal="11-29 28 39"/>
    <eLiterals name="_11292843" value="383" literal="11-29 28 43"/>
    <eLiterals name="_11292847" value="384" literal="11-29 28 47"/>
    <eLiterals name="_11292851" value="385" literal="11-29 28 51"/>
    <eLiterals name="_11292855" value="386" literal="11-29 28 55"/>
    <eLiterals name="_1129285511" value="387" literal="11-29 28 55 11"/>
    <eLiterals name="_1129285515" value="388" literal="11-29 28 55 15"/>
    <eLiterals name="_1129285521" value="389" literal="11-29 28 55 21"/>
    <eLiterals name="_11292859" value="390" literal="11-29 28 59"/>
    <eLiterals name="_1129285911" value="391" literal="11-29 28 59 11"/>
    <eLiterals name="_11292863" value="392" literal="11-29 28 63"/>
    <eLiterals name="_11292867" value="393" literal="11-29 28 67"/>
    <eLiterals name="_11292871" value="394" literal="11-29 28 71"/>
    <eLiterals name="_1129287111" value="395" literal="11-29 28 71 11"/>
    <eLiterals name="_1129287115" value="396" literal="11-29 28 71 15"/>
    <eLiterals name="_1129287119" value="397" literal="11-29 28 71 19"/>
    <eLiterals name="_1129287123" value="398" literal="11-29 28 71 23"/>
    <eLiterals name="_1129287127" value="399" literal="11-29 28 71 27"/>
    <eLiterals name="_1129287131" value="400" literal="11-29 28 71 31"/>
    <eLiterals name="_11350000" value="401" literal="11-35 00 00"/>
    <eLiterals name="_11351100" value="402" literal="11-35 11 00"/>
    <eLiterals name="_11351111" value="403" literal="11-35 11 11"/>
    <eLiterals name="_11351114" value="404" literal="11-35 11 14"/>
    <eLiterals name="_11351117" value="405" literal="11-35 11 17"/>
    <eLiterals name="_11351121" value="406" literal="11-35 11 21"/>
    <eLiterals name="_11351123" value="407" literal="11-35 11 23"/>
    <eLiterals name="_11351126" value="408" literal="11-35 11 26"/>
    <eLiterals name="_11351129" value="409" literal="11-35 11 29"/>
    <eLiterals name="_11351132" value="410" literal="11-35 11 32"/>
    <eLiterals name="_11351135" value="411" literal="11-35 11 35"/>
    <eLiterals name="_11351138" value="412" literal="11-35 11 38"/>
    <eLiterals name="_11351141" value="413" literal="11-35 11 41"/>
    <eLiterals name="_11351144" value="414" literal="11-35 11 44"/>
    <eLiterals name="_11351147" value="415" literal="11-35 11 47"/>
    <eLiterals name="_11351151" value="416" literal="11-35 11 51"/>
    <eLiterals name="_11351153" value="417" literal="11-35 11 53"/>
    <eLiterals name="_11351156" value="418" literal="11-35 11 56"/>
    <eLiterals name="_11351159" value="419" literal="11-35 11 59"/>
    <eLiterals name="_11351162" value="420" literal="11-35 11 62"/>
    <eLiterals name="_11351165" value="421" literal="11-35 11 65"/>
    <eLiterals name="_11351168" value="422" literal="11-35 11 68"/>
    <eLiterals name="_11351171" value="423" literal="11-35 11 71"/>
    <eLiterals name="_11351174" value="424" literal="11-35 11 74"/>
    <eLiterals name="_11351177" value="425" literal="11-35 11 77"/>
    <eLiterals name="_11351181" value="426" literal="11-35 11 81"/>
    <eLiterals name="_11351183" value="427" literal="11-35 11 83"/>
    <eLiterals name="_11351186" value="428" literal="11-35 11 86"/>
    <eLiterals name="_11351189" value="429" literal="11-35 11 89"/>
    <eLiterals name="_11351500" value="430" literal="11-35 15 00"/>
    <eLiterals name="_11351511" value="431" literal="11-35 15 11"/>
    <eLiterals name="_11351515" value="432" literal="11-35 15 15"/>
    <eLiterals name="_11351519" value="433" literal="11-35 15 19"/>
    <eLiterals name="_11351523" value="434" literal="11-35 15 23"/>
    <eLiterals name="_11351527" value="435" literal="11-35 15 27"/>
    <eLiterals name="_11351531" value="436" literal="11-35 15 31"/>
    <eLiterals name="_11351535" value="437" literal="11-35 15 35"/>
    <eLiterals name="_11351539" value="438" literal="11-35 15 39"/>
    <eLiterals name="_11351543" value="439" literal="11-35 15 43"/>
    <eLiterals name="_11351547" value="440" literal="11-35 15 47"/>
    <eLiterals name="_11351551" value="441" literal="11-35 15 51"/>
    <eLiterals name="_11351555" value="442" literal="11-35 15 55"/>
    <eLiterals name="_11351559" value="443" literal="11-35 15 59"/>
    <eLiterals name="_11351563" value="444" literal="11-35 15 63"/>
    <eLiterals name="_11351567" value="445" literal="11-35 15 67"/>
    <eLiterals name="_11351900" value="446" literal="11-35 19 00"/>
    <eLiterals name="_11351921" value="447" literal="11-35 19 21"/>
    <eLiterals name="_11351931" value="448" literal="11-35 19 31"/>
    <eLiterals name="_11352300" value="449" literal="11-35 23 00"/>
    <eLiterals name="_11352311" value="450" literal="11-35 23 11"/>
    <eLiterals name="_11352315" value="451" literal="11-35 23 15"/>
    <eLiterals name="_11352319" value="452" literal="11-35 23 19"/>
    <eLiterals name="_11352323" value="453" literal="11-35 23 23"/>
    <eLiterals name="_11352327" value="454" literal="11-35 23 27"/>
    <eLiterals name="_11352331" value="455" literal="11-35 23 31"/>
    <eLiterals name="_11355500" value="456" literal="11-35 55 00"/>
    <eLiterals name="_11355511" value="457" literal="11-35 55 11"/>
    <eLiterals name="_11355521" value="458" literal="11-35 55 21"/>
    <eLiterals name="_11355531" value="459" literal="11-35 55 31"/>
    <eLiterals name="_11370000" value="460" literal="11-37 00 00"/>
    <eLiterals name="_11371200" value="461" literal="11-37 12 00"/>
    <eLiterals name="_11371211" value="462" literal="11-37 12 11"/>
    <eLiterals name="_11371215" value="463" literal="11-37 12 15"/>
    <eLiterals name="_11371219" value="464" literal="11-37 12 19"/>
    <eLiterals name="_11371223" value="465" literal="11-37 12 23"/>
    <eLiterals name="_11371227" value="466" literal="11-37 12 27"/>
    <eLiterals name="_11371231" value="467" literal="11-37 12 31"/>
    <eLiterals name="_11371235" value="468" literal="11-37 12 35"/>
    <eLiterals name="_11371239" value="469" literal="11-37 12 39"/>
    <eLiterals name="_11371243" value="470" literal="11-37 12 43"/>
    <eLiterals name="_11371500" value="471" literal="11-37 15 00"/>
    <eLiterals name="_11371900" value="472" literal="11-37 19 00"/>
    <eLiterals name="_11372300" value="473" literal="11-37 23 00"/>
    <eLiterals name="_11372600" value="474" literal="11-37 26 00"/>
    <eLiterals name="_11372611" value="475" literal="11-37 26 11"/>
    <eLiterals name="_11372615" value="476" literal="11-37 26 15"/>
    <eLiterals name="_11373200" value="477" literal="11-37 32 00"/>
    <eLiterals name="_11373211" value="478" literal="11-37 32 11"/>
    <eLiterals name="_11373215" value="479" literal="11-37 32 15"/>
    <eLiterals name="_11373500" value="480" literal="11-37 35 00"/>
    <eLiterals name="_11373511" value="481" literal="11-37 35 11"/>
    <eLiterals name="_11373521" value="482" literal="11-37 35 21"/>
    <eLiterals name="_11373531" value="483" literal="11-37 35 31"/>
    <eLiterals name="_11373900" value="484" literal="11-37 39 00"/>
    <eLiterals name="_11373911" value="485" literal="11-37 39 11"/>
    <eLiterals name="_11373921" value="486" literal="11-37 39 21"/>
    <eLiterals name="_11373931" value="487" literal="11-37 39 31"/>
    <eLiterals name="_11374500" value="488" literal="11-37 45 00"/>
    <eLiterals name="_11374511" value="489" literal="11-37 45 11"/>
    <eLiterals name="_11374515" value="490" literal="11-37 45 15"/>
    <eLiterals name="_11374519" value="491" literal="11-37 45 19"/>
    <eLiterals name="_11374900" value="492" literal="11-37 49 00"/>
    <eLiterals name="_11374911" value="493" literal="11-37 49 11"/>
    <eLiterals name="_11375500" value="494" literal="11-37 55 00"/>
    <eLiterals name="_11375511" value="495" literal="11-37 55 11"/>
    <eLiterals name="_11376500" value="496" literal="11-37 65 00"/>
    <eLiterals name="_11376511" value="497" literal="11-37 65 11"/>
    <eLiterals name="_11376515" value="498" literal="11-37 65 15"/>
    <eLiterals name="_11376519" value="499" literal="11-37 65 19"/>
    <eLiterals name="_11376523" value="500" literal="11-37 65 23"/>
    <eLiterals name="_11376527" value="501" literal="11-37 65 27"/>
    <eLiterals name="_11376531" value="502" literal="11-37 65 31"/>
    <eLiterals name="_11410000" value="503" literal="11-41 00 00"/>
    <eLiterals name="_11411100" value="504" literal="11-41 11 00"/>
    <eLiterals name="_11411111" value="505" literal="11-41 11 11"/>
    <eLiterals name="_11411114" value="506" literal="11-41 11 14"/>
    <eLiterals name="_11411117" value="507" literal="11-41 11 17"/>
    <eLiterals name="_11411125" value="508" literal="11-41 11 25"/>
    <eLiterals name="_11412100" value="509" literal="11-41 21 00"/>
    <eLiterals name="_11412111" value="510" literal="11-41 21 11"/>
    <eLiterals name="_11412114" value="511" literal="11-41 21 14"/>
    <eLiterals name="_11412117" value="512" literal="11-41 21 17"/>
    <eLiterals name="_11412121" value="513" literal="11-41 21 21"/>
    <eLiterals name="_11412124" value="514" literal="11-41 21 24"/>
    <eLiterals name="_11412127" value="515" literal="11-41 21 27"/>
    <eLiterals name="_11412131" value="516" literal="11-41 21 31"/>
    <eLiterals name="_11412135" value="517" literal="11-41 21 35"/>
    <eLiterals name="_11412139" value="518" literal="11-41 21 39"/>
    <eLiterals name="_11412400" value="519" literal="11-41 24 00"/>
    <eLiterals name="_11412411" value="520" literal="11-41 24 11"/>
    <eLiterals name="_11412414" value="521" literal="11-41 24 14"/>
    <eLiterals name="_11412417" value="522" literal="11-41 24 17"/>
    <eLiterals name="_11412700" value="523" literal="11-41 27 00"/>
    <eLiterals name="_11412711" value="524" literal="11-41 27 11"/>
    <eLiterals name="_11412714" value="525" literal="11-41 27 14"/>
    <eLiterals name="_11412717" value="526" literal="11-41 27 17"/>
    <eLiterals name="_11413500" value="527" literal="11-41 35 00"/>
    <eLiterals name="_11413511" value="528" literal="11-41 35 11"/>
    <eLiterals name="_11413515" value="529" literal="11-41 35 15"/>
    <eLiterals name="_11413519" value="530" literal="11-41 35 19"/>
    <eLiterals name="_11413523" value="531" literal="11-41 35 23"/>
    <eLiterals name="_11413527" value="532" literal="11-41 35 27"/>
    <eLiterals name="_11413900" value="533" literal="11-41 39 00"/>
    <eLiterals name="_11413911" value="534" literal="11-41 39 11"/>
    <eLiterals name="_11414300" value="535" literal="11-41 43 00"/>
    <eLiterals name="_11414311" value="536" literal="11-41 43 11"/>
    <eLiterals name="_11414700" value="537" literal="11-41 47 00"/>
    <eLiterals name="_11414711" value="538" literal="11-41 47 11"/>
    <eLiterals name="_11420000" value="539" literal="11-42 00 00"/>
    <eLiterals name="_11421100" value="540" literal="11-42 11 00"/>
    <eLiterals name="_11421111" value="541" literal="11-42 11 11"/>
    <eLiterals name="_11421114" value="542" literal="11-42 11 14"/>
    <eLiterals name="_11421117" value="543" literal="11-42 11 17"/>
    <eLiterals name="_11421121" value="544" literal="11-42 11 21"/>
    <eLiterals name="_11421124" value="545" literal="11-42 11 24"/>
    <eLiterals name="_11421127" value="546" literal="11-42 11 27"/>
    <eLiterals name="_11421131" value="547" literal="11-42 11 31"/>
    <eLiterals name="_11421134" value="548" literal="11-42 11 34"/>
    <eLiterals name="_11421137" value="549" literal="11-42 11 37"/>
    <eLiterals name="_11421155" value="550" literal="11-42 11 55"/>
    <eLiterals name="_11422100" value="551" literal="11-42 21 00"/>
    <eLiterals name="_11422111" value="552" literal="11-42 21 11"/>
    <eLiterals name="_11422114" value="553" literal="11-42 21 14"/>
    <eLiterals name="_11422121" value="554" literal="11-42 21 21"/>
    <eLiterals name="_11422124" value="555" literal="11-42 21 24"/>
    <eLiterals name="_11422129" value="556" literal="11-42 21 29"/>
    <eLiterals name="_11422400" value="557" literal="11-42 24 00"/>
    <eLiterals name="_11422411" value="558" literal="11-42 24 11"/>
    <eLiterals name="_11422414" value="559" literal="11-42 24 14"/>
    <eLiterals name="_11422417" value="560" literal="11-42 24 17"/>
    <eLiterals name="_11422421" value="561" literal="11-42 24 21"/>
    <eLiterals name="_11422425" value="562" literal="11-42 24 25"/>
    <eLiterals name="_11422700" value="563" literal="11-42 27 00"/>
    <eLiterals name="_11422711" value="564" literal="11-42 27 11"/>
    <eLiterals name="_11422714" value="565" literal="11-42 27 14"/>
    <eLiterals name="_11422717" value="566" literal="11-42 27 17"/>
    <eLiterals name="_11422721" value="567" literal="11-42 27 21"/>
    <eLiterals name="_11422724" value="568" literal="11-42 27 24"/>
    <eLiterals name="_11422727" value="569" literal="11-42 27 27"/>
    <eLiterals name="_11422732" value="570" literal="11-42 27 32"/>
    <eLiterals name="_11422735" value="571" literal="11-42 27 35"/>
    <eLiterals name="_11422739" value="572" literal="11-42 27 39"/>
    <eLiterals name="_11423800" value="573" literal="11-42 38 00"/>
    <eLiterals name="_11423811" value="574" literal="11-42 38 11"/>
    <eLiterals name="_11423815" value="575" literal="11-42 38 15"/>
    <eLiterals name="_11423819" value="576" literal="11-42 38 19"/>
    <eLiterals name="_11423823" value="577" literal="11-42 38 23"/>
    <eLiterals name="_11423827" value="578" literal="11-42 38 27"/>
    <eLiterals name="_11423831" value="579" literal="11-42 38 31"/>
    <eLiterals name="_11423835" value="580" literal="11-42 38 35"/>
    <eLiterals name="_11423839" value="581" literal="11-42 38 39"/>
    <eLiterals name="_11430000" value="582" literal="11-43 00 00"/>
    <eLiterals name="_11431100" value="583" literal="11-43 11 00"/>
    <eLiterals name="_11431105" value="584" literal="11-43 11 05"/>
    <eLiterals name="_11431108" value="585" literal="11-43 11 08"/>
    <eLiterals name="_11431111" value="586" literal="11-43 11 11"/>
    <eLiterals name="_11431112" value="587" literal="11-43 11 12"/>
    <eLiterals name="_11431114" value="588" literal="11-43 11 14"/>
    <eLiterals name="_11431125" value="589" literal="11-43 11 25"/>
    <eLiterals name="_11432100" value="590" literal="11-43 21 00"/>
    <eLiterals name="_11432111" value="591" literal="11-43 21 11"/>
    <eLiterals name="_11432114" value="592" literal="11-43 21 14"/>
    <eLiterals name="_11432117" value="593" literal="11-43 21 17"/>
    <eLiterals name="_11432121" value="594" literal="11-43 21 21"/>
    <eLiterals name="_11432123" value="595" literal="11-43 21 23"/>
    <eLiterals name="_11432126" value="596" literal="11-43 21 26"/>
    <eLiterals name="_11432129" value="597" literal="11-43 21 29"/>
    <eLiterals name="_11432132" value="598" literal="11-43 21 32"/>
    <eLiterals name="_11440000" value="599" literal="11-44 00 00"/>
    <eLiterals name="_11441100" value="600" literal="11-44 11 00"/>
    <eLiterals name="_11441111" value="601" literal="11-44 11 11"/>
    <eLiterals name="_11441114" value="602" literal="11-44 11 14"/>
    <eLiterals name="_11441117" value="603" literal="11-44 11 17"/>
    <eLiterals name="_11441121" value="604" literal="11-44 11 21"/>
    <eLiterals name="_11441124" value="605" literal="11-44 11 24"/>
    <eLiterals name="_11441127" value="606" literal="11-44 11 27"/>
    <eLiterals name="_11441175" value="607" literal="11-44 11 75"/>
    <eLiterals name="_11442100" value="608" literal="11-44 21 00"/>
    <eLiterals name="_11442111" value="609" literal="11-44 21 11"/>
    <eLiterals name="_11442114" value="610" literal="11-44 21 14"/>
    <eLiterals name="_11445500" value="611" literal="11-44 55 00"/>
    <eLiterals name="_11445511" value="612" literal="11-44 55 11"/>
    <eLiterals name="_11445515" value="613" literal="11-44 55 15"/>
    <eLiterals name="_11445519" value="614" literal="11-44 55 19"/>
    <eLiterals name="_11510000" value="615" literal="11-51 00 00"/>
    <eLiterals name="_11511100" value="616" literal="11-51 11 00"/>
    <eLiterals name="_11511111" value="617" literal="11-51 11 11"/>
    <eLiterals name="_11511114" value="618" literal="11-51 11 14"/>
    <eLiterals name="_11511117" value="619" literal="11-51 11 17"/>
    <eLiterals name="_11511121" value="620" literal="11-51 11 21"/>
    <eLiterals name="_11511124" value="621" literal="11-51 11 24"/>
    <eLiterals name="_11511127" value="622" literal="11-51 11 27"/>
    <eLiterals name="_11511135" value="623" literal="11-51 11 35"/>
    <eLiterals name="_11511139" value="624" literal="11-51 11 39"/>
    <eLiterals name="_11511143" value="625" literal="11-51 11 43"/>
    <eLiterals name="_11511147" value="626" literal="11-51 11 47"/>
    <eLiterals name="_11512100" value="627" literal="11-51 21 00"/>
    <eLiterals name="_11512111" value="628" literal="11-51 21 11"/>
    <eLiterals name="_11512112" value="629" literal="11-51 21 12"/>
    <eLiterals name="_11512114" value="630" literal="11-51 21 14"/>
    <eLiterals name="_11512115" value="631" literal="11-51 21 15"/>
    <eLiterals name="_11512117" value="632" literal="11-51 21 17"/>
    <eLiterals name="_11512121" value="633" literal="11-51 21 21"/>
    <eLiterals name="_11512123" value="634" literal="11-51 21 23"/>
    <eLiterals name="_11512400" value="635" literal="11-51 24 00"/>
    <eLiterals name="_11512411" value="636" literal="11-51 24 11"/>
    <eLiterals name="_11512414" value="637" literal="11-51 24 14"/>
    <eLiterals name="_11512417" value="638" literal="11-51 24 17"/>
    <eLiterals name="_11512435" value="639" literal="11-51 24 35"/>
    <eLiterals name="_11512700" value="640" literal="11-51 27 00"/>
    <eLiterals name="_11512711" value="641" literal="11-51 27 11"/>
    <eLiterals name="_11512714" value="642" literal="11-51 27 14"/>
    <eLiterals name="_11512715" value="643" literal="11-51 27 15"/>
    <eLiterals name="_11512717" value="644" literal="11-51 27 17"/>
    <eLiterals name="_11512718" value="645" literal="11-51 27 18"/>
    <eLiterals name="_11512721" value="646" literal="11-51 27 21"/>
    <eLiterals name="_11513100" value="647" literal="11-51 31 00"/>
    <eLiterals name="_11513111" value="648" literal="11-51 31 11"/>
    <eLiterals name="_11513112" value="649" literal="11-51 31 12"/>
    <eLiterals name="_11513114" value="650" literal="11-51 31 14"/>
    <eLiterals name="_11513117" value="651" literal="11-51 31 17"/>
    <eLiterals name="_11513118" value="652" literal="11-51 31 18"/>
    <eLiterals name="_11513121" value="653" literal="11-51 31 21"/>
    <eLiterals name="_11513124" value="654" literal="11-51 31 24"/>
    <eLiterals name="_11513129" value="655" literal="11-51 31 29"/>
    <eLiterals name="_11513133" value="656" literal="11-51 31 33"/>
    <eLiterals name="_11513137" value="657" literal="11-51 31 37"/>
    <eLiterals name="_11513141" value="658" literal="11-51 31 41"/>
    <eLiterals name="_11513400" value="659" literal="11-51 34 00"/>
    <eLiterals name="_11513415" value="660" literal="11-51 34 15"/>
    <eLiterals name="_11513419" value="661" literal="11-51 34 19"/>
    <eLiterals name="_11513423" value="662" literal="11-51 34 23"/>
    <eLiterals name="_11514500" value="663" literal="11-51 45 00"/>
    <eLiterals name="_11514511" value="664" literal="11-51 45 11"/>
    <eLiterals name="_11514515" value="665" literal="11-51 45 15"/>
    <eLiterals name="_11514519" value="666" literal="11-51 45 19"/>
    <eLiterals name="_11514523" value="667" literal="11-51 45 23"/>
    <eLiterals name="_11514527" value="668" literal="11-51 45 27"/>
    <eLiterals name="_11514531" value="669" literal="11-51 45 31"/>
    <eLiterals name="_11514535" value="670" literal="11-51 45 35"/>
    <eLiterals name="_11514539" value="671" literal="11-51 45 39"/>
    <eLiterals name="_11514543" value="672" literal="11-51 45 43"/>
    <eLiterals name="_11514900" value="673" literal="11-51 49 00"/>
    <eLiterals name="_11514911" value="674" literal="11-51 49 11"/>
    <eLiterals name="_11514915" value="675" literal="11-51 49 15"/>
    <eLiterals name="_11515300" value="676" literal="11-51 53 00"/>
    <eLiterals name="_11515311" value="677" literal="11-51 53 11"/>
    <eLiterals name="_11515313" value="678" literal="11-51 53 13"/>
    <eLiterals name="_11515315" value="679" literal="11-51 53 15"/>
    <eLiterals name="_11515319" value="680" literal="11-51 53 19"/>
    <eLiterals name="_11515800" value="681" literal="11-51 58 00"/>
    <eLiterals name="_11515811" value="682" literal="11-51 58 11"/>
    <eLiterals name="_11515815" value="683" literal="11-51 58 15"/>
    <eLiterals name="_11515819" value="684" literal="11-51 58 19"/>
    <eLiterals name="_11515823" value="685" literal="11-51 58 23"/>
    <eLiterals name="_11515827" value="686" literal="11-51 58 27"/>
    <eLiterals name="_11515831" value="687" literal="11-51 58 31"/>
    <eLiterals name="_11516500" value="688" literal="11-51 65 00"/>
    <eLiterals name="_11516511" value="689" literal="11-51 65 11"/>
    <eLiterals name="_11516515" value="690" literal="11-51 65 15"/>
    <eLiterals name="_11516519" value="691" literal="11-51 65 19"/>
    <eLiterals name="_11516700" value="692" literal="11-51 67 00"/>
    <eLiterals name="_11516711" value="693" literal="11-51 67 11"/>
    <eLiterals name="_11516715" value="694" literal="11-51 67 15"/>
    <eLiterals name="_11516719" value="695" literal="11-51 67 19"/>
    <eLiterals name="_11517500" value="696" literal="11-51 75 00"/>
    <eLiterals name="_11517511" value="697" literal="11-51 75 11"/>
    <eLiterals name="_11517515" value="698" literal="11-51 75 15"/>
    <eLiterals name="_11517519" value="699" literal="11-51 75 19"/>
    <eLiterals name="_11900000" value="700" literal="11-90 00 00"/>
    <eLiterals name="_11901100" value="701" literal="11-90 11 00"/>
    <eLiterals name="_11950000" value="702" literal="11-95 00 00"/>
    <eLiterals name="_11951100" value="703" literal="11-95 11 00"/>
    <eLiterals name="_11951111" value="704" literal="11-95 11 11"/>
    <eLiterals name="_11951115" value="705" literal="11-95 11 15"/>
    <eLiterals name="_11951119" value="706" literal="11-95 11 19"/>
    <eLiterals name="_11951123" value="707" literal="11-95 11 23"/>
    <eLiterals name="_11951127" value="708" literal="11-95 11 27"/>
    <eLiterals name="_11951500" value="709" literal="11-95 15 00"/>
    <eLiterals name="_11951900" value="710" literal="11-95 19 00"/>
    <eLiterals name="_11951911" value="711" literal="11-95 19 11"/>
    <eLiterals name="_11951915" value="712" literal="11-95 19 15"/>
    <eLiterals name="_11951919" value="713" literal="11-95 19 19"/>
    <eLiterals name="_11952300" value="714" literal="11-95 23 00"/>
    <eLiterals name="_11952311" value="715" literal="11-95 23 11"/>
    <eLiterals name="_11952315" value="716" literal="11-95 23 15"/>
    <eLiterals name="_11952319" value="717" literal="11-95 23 19"/>
    <eLiterals name="_11952323" value="718" literal="11-95 23 23"/>
    <eLiterals name="_11952327" value="719" literal="11-95 23 27"/>
    <eLiterals name="_11952333" value="720" literal="11-95 23 33"/>
    <eLiterals name="_11952700" value="721" literal="11-95 27 00"/>
    <eLiterals name="_11953100" value="722" literal="11-95 31 00"/>
    <eLiterals name="_11953500" value="723" literal="11-95 35 00"/>
    <eLiterals name="_11953900" value="724" literal="11-95 39 00"/>
    <eLiterals name="_11954300" value="725" literal="11-95 43 00"/>
    <eLiterals name="_11954700" value="726" literal="11-95 47 00"/>
    <eLiterals name="_11955100" value="727" literal="11-95 51 00"/>
    <eLiterals name="_11955500" value="728" literal="11-95 55 00"/>
    <eLiterals name="_11955900" value="729" literal="11-95 59 00"/>
    <eLiterals name="_11956300" value="730" literal="11-95 63 00"/>
    <eLiterals name="_11956700" value="731" literal="11-95 67 00"/>
    <eLiterals name="_11957100" value="732" literal="11-95 71 00"/>
    <eLiterals name="_11957111" value="733" literal="11-95 71 11"/>
    <eLiterals name="_11957115" value="734" literal="11-95 71 15"/>
    <eLiterals name="_11957119" value="735" literal="11-95 71 19"/>
    <eLiterals name="_11957500" value="736" literal="11-95 75 00"/>
    <eLiterals name="_11957900" value="737" literal="11-95 79 00"/>
    <eLiterals name="_11958300" value="738" literal="11-95 83 00"/>
    <eLiterals name="_11958311" value="739" literal="11-95 83 11"/>
    <eLiterals name="_11958315" value="740" literal="11-95 83 15"/>
    <eLiterals name="_11958319" value="741" literal="11-95 83 19"/>
    <eLiterals name="_11958700" value="742" literal="11-95 87 00"/>
    <eLiterals name="_11959100" value="743" literal="11-95 91 00"/>
    <eLiterals name="_11959111" value="744" literal="11-95 91 11"/>
    <eLiterals name="_11959115" value="745" literal="11-95 91 15"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FacilityUsageCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageCodeSimpleType:Object"/>
      <details key="baseType" value="FacilityUsageCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacilityUsageCodeType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//FacilityUsageCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FacilityUsageLevel1CodeSimpleType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageLevel1CodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_11110000" literal="11-11 00 00"/>
    <eLiterals name="_11120000" value="1" literal="11-12 00 00"/>
    <eLiterals name="_11130000" value="2" literal="11-13 00 00"/>
    <eLiterals name="_11140000" value="3" literal="11-14 00 00"/>
    <eLiterals name="_11150000" value="4" literal="11-15 00 00"/>
    <eLiterals name="_11160000" value="5" literal="11-16 00 00"/>
    <eLiterals name="_11170000" value="6" literal="11-17 00 00"/>
    <eLiterals name="_11210000" value="7" literal="11-21 00 00"/>
    <eLiterals name="_11230000" value="8" literal="11-23 00 00"/>
    <eLiterals name="_11250000" value="9" literal="11-25 00 00"/>
    <eLiterals name="_11270000" value="10" literal="11-27 00 00"/>
    <eLiterals name="_11290000" value="11" literal="11-29 00 00"/>
    <eLiterals name="_11350000" value="12" literal="11-35 00 00"/>
    <eLiterals name="_11370000" value="13" literal="11-37 00 00"/>
    <eLiterals name="_11410000" value="14" literal="11-41 00 00"/>
    <eLiterals name="_11430000" value="15" literal="11-43 00 00"/>
    <eLiterals name="_11440000" value="16" literal="11-44 00 00"/>
    <eLiterals name="_11510000" value="17" literal="11-51 00 00"/>
    <eLiterals name="_11900000" value="18" literal="11-90 00 00"/>
    <eLiterals name="_11950000" value="19" literal="11-95 00 00"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FacilityUsageLevel1CodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageLevel1CodeSimpleType:Object"/>
      <details key="baseType" value="FacilityUsageLevel1CodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacilityUsageLevel1CodeType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageLevel1CodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//FacilityUsageLevel1CodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FacilityUsageLevel2CodeSimpleType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageLevel2CodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_11110000" literal="11-11 00 00"/>
    <eLiterals name="_11111111" value="1" literal="11-11 11 11"/>
    <eLiterals name="_11112111" value="2" literal="11-11 21 11"/>
    <eLiterals name="_11112117" value="3" literal="11-11 21 17"/>
    <eLiterals name="_11112121" value="4" literal="11-11 21 21"/>
    <eLiterals name="_11112122" value="5" literal="11-11 21 22"/>
    <eLiterals name="_11112123" value="6" literal="11-11 21 23"/>
    <eLiterals name="_11112124" value="7" literal="11-11 21 24"/>
    <eLiterals name="_11112127" value="8" literal="11-11 21 27"/>
    <eLiterals name="_11120000" value="9" literal="11-12 00 00"/>
    <eLiterals name="_11121111" value="10" literal="11-12 11 11"/>
    <eLiterals name="_11121114" value="11" literal="11-12 11 14"/>
    <eLiterals name="_11122114" value="12" literal="11-12 21 14"/>
    <eLiterals name="_11122121" value="13" literal="11-12 21 21"/>
    <eLiterals name="_11122131" value="14" literal="11-12 21 31"/>
    <eLiterals name="_11122411" value="15" literal="11-12 24 11"/>
    <eLiterals name="_11122900" value="16" literal="11-12 29 00"/>
    <eLiterals name="_11130000" value="17" literal="11-13 00 00"/>
    <eLiterals name="_11131100" value="18" literal="11-13 11 00"/>
    <eLiterals name="_11131114" value="19" literal="11-13 11 14"/>
    <eLiterals name="_11131117" value="20" literal="11-13 11 17"/>
    <eLiterals name="_11131121" value="21" literal="11-13 11 21"/>
    <eLiterals name="_11131123" value="22" literal="11-13 11 23"/>
    <eLiterals name="_1113112311" value="23" literal="11-13 11 23 11"/>
    <eLiterals name="_1113112314" value="24" literal="11-13 11 23 14"/>
    <eLiterals name="_11131124" value="25" literal="11-13 11 24"/>
    <eLiterals name="_1113112411" value="26" literal="11-13 11 24 11"/>
    <eLiterals name="_1113112414" value="27" literal="11-13 11 24 14"/>
    <eLiterals name="_1113112417" value="28" literal="11-13 11 24 17"/>
    <eLiterals name="_11131127" value="29" literal="11-13 11 27"/>
    <eLiterals name="_11131131" value="30" literal="11-13 11 31"/>
    <eLiterals name="_11131133" value="31" literal="11-13 11 33"/>
    <eLiterals name="_1113113311" value="32" literal="11-13 11 33 11"/>
    <eLiterals name="_1113113314" value="33" literal="11-13 11 33 14"/>
    <eLiterals name="_1113113317" value="34" literal="11-13 11 33 17"/>
    <eLiterals name="_1113113321" value="35" literal="11-13 11 33 21"/>
    <eLiterals name="_11131134" value="36" literal="11-13 11 34"/>
    <eLiterals name="_11132100" value="37" literal="11-13 21 00"/>
    <eLiterals name="_11132711" value="38" literal="11-13 27 11"/>
    <eLiterals name="_11132714" value="39" literal="11-13 27 14"/>
    <eLiterals name="_11132726" value="40" literal="11-13 27 26"/>
    <eLiterals name="_11132911" value="41" literal="11-13 29 11"/>
    <eLiterals name="_11132914" value="42" literal="11-13 29 14"/>
    <eLiterals name="_11140000" value="43" literal="11-14 00 00"/>
    <eLiterals name="_11141500" value="44" literal="11-14 15 00"/>
    <eLiterals name="_11142100" value="45" literal="11-14 21 00"/>
    <eLiterals name="_11142411" value="46" literal="11-14 24 11"/>
    <eLiterals name="_11150000" value="47" literal="11-15 00 00"/>
    <eLiterals name="_11151100" value="48" literal="11-15 11 00"/>
    <eLiterals name="_1115113615" value="49" literal="11-15 11 36 15"/>
    <eLiterals name="_11151139" value="50" literal="11-15 11 39"/>
    <eLiterals name="_11152100" value="51" literal="11-15 21 00"/>
    <eLiterals name="_1115213711" value="52" literal="11-15 21 37 11"/>
    <eLiterals name="_1115213714" value="53" literal="11-15 21 37 14"/>
    <eLiterals name="_11160000" value="54" literal="11-16 00 00"/>
    <eLiterals name="_11161100" value="55" literal="11-16 11 00"/>
    <eLiterals name="_11161111" value="56" literal="11-16 11 11"/>
    <eLiterals name="_11161114" value="57" literal="11-16 11 14"/>
    <eLiterals name="_11161511" value="58" literal="11-16 15 11"/>
    <eLiterals name="_11162100" value="59" literal="11-16 21 00"/>
    <eLiterals name="_11162114" value="60" literal="11-16 21 14"/>
    <eLiterals name="_11162117" value="61" literal="11-16 21 17"/>
    <eLiterals name="_11162121" value="62" literal="11-16 21 21"/>
    <eLiterals name="_11162125" value="63" literal="11-16 21 25"/>
    <eLiterals name="_11162129" value="64" literal="11-16 21 29"/>
    <eLiterals name="_11162700" value="65" literal="11-16 27 00"/>
    <eLiterals name="_11163100" value="66" literal="11-16 31 00"/>
    <eLiterals name="_11164200" value="67" literal="11-16 42 00"/>
    <eLiterals name="_11170000" value="68" literal="11-17 00 00"/>
    <eLiterals name="_11170500" value="69" literal="11-17 05 00"/>
    <eLiterals name="_11170700" value="70" literal="11-17 07 00"/>
    <eLiterals name="_11170900" value="71" literal="11-17 09 00"/>
    <eLiterals name="_11171100" value="72" literal="11-17 11 00"/>
    <eLiterals name="_11171111" value="73" literal="11-17 11 11"/>
    <eLiterals name="_11171113" value="74" literal="11-17 11 13"/>
    <eLiterals name="_11171300" value="75" literal="11-17 13 00"/>
    <eLiterals name="_11171500" value="76" literal="11-17 15 00"/>
    <eLiterals name="_11171700" value="77" literal="11-17 17 00"/>
    <eLiterals name="_11171913" value="78" literal="11-17 19 13"/>
    <eLiterals name="_11172114" value="79" literal="11-17 21 14"/>
    <eLiterals name="_11172711" value="80" literal="11-17 27 11"/>
    <eLiterals name="_11172714" value="81" literal="11-17 27 14"/>
    <eLiterals name="_11172723" value="82" literal="11-17 27 23"/>
    <eLiterals name="_11172726" value="83" literal="11-17 27 26"/>
    <eLiterals name="_11172729" value="84" literal="11-17 27 29"/>
    <eLiterals name="_11172735" value="85" literal="11-17 27 35"/>
    <eLiterals name="_11210000" value="86" literal="11-21 00 00"/>
    <eLiterals name="_11211200" value="87" literal="11-21 12 00"/>
    <eLiterals name="_11211500" value="88" literal="11-21 15 00"/>
    <eLiterals name="_11211700" value="89" literal="11-21 17 00"/>
    <eLiterals name="_11212800" value="90" literal="11-21 28 00"/>
    <eLiterals name="_11213200" value="91" literal="11-21 32 00"/>
    <eLiterals name="_11213211" value="92" literal="11-21 32 11"/>
    <eLiterals name="_11213215" value="93" literal="11-21 32 15"/>
    <eLiterals name="_11213500" value="94" literal="11-21 35 00"/>
    <eLiterals name="_11213800" value="95" literal="11-21 38 00"/>
    <eLiterals name="_11214500" value="96" literal="11-21 45 00"/>
    <eLiterals name="_11215511" value="97" literal="11-21 55 11"/>
    <eLiterals name="_11215519" value="98" literal="11-21 55 19"/>
    <eLiterals name="_11230000" value="99" literal="11-23 00 00"/>
    <eLiterals name="_11231200" value="100" literal="11-23 12 00"/>
    <eLiterals name="_11231211" value="101" literal="11-23 12 11"/>
    <eLiterals name="_11231231" value="102" literal="11-23 12 31"/>
    <eLiterals name="_11231235" value="103" literal="11-23 12 35"/>
    <eLiterals name="_11231243" value="104" literal="11-23 12 43"/>
    <eLiterals name="_11231500" value="105" literal="11-23 15 00"/>
    <eLiterals name="_11231800" value="106" literal="11-23 18 00"/>
    <eLiterals name="_11250000" value="107" literal="11-25 00 00"/>
    <eLiterals name="_11251200" value="108" literal="11-25 12 00"/>
    <eLiterals name="_11251215" value="109" literal="11-25 12 15"/>
    <eLiterals name="_11251219" value="110" literal="11-25 12 19"/>
    <eLiterals name="_11251223" value="111" literal="11-25 12 23"/>
    <eLiterals name="_11251227" value="112" literal="11-25 12 27"/>
    <eLiterals name="_11251243" value="113" literal="11-25 12 43"/>
    <eLiterals name="_11251247" value="114" literal="11-25 12 47"/>
    <eLiterals name="_11251251" value="115" literal="11-25 12 51"/>
    <eLiterals name="_11251267" value="116" literal="11-25 12 67"/>
    <eLiterals name="_11255500" value="117" literal="11-25 55 00"/>
    <eLiterals name="_11270000" value="118" literal="11-27 00 00"/>
    <eLiterals name="_11271200" value="119" literal="11-27 12 00"/>
    <eLiterals name="_11271800" value="120" literal="11-27 18 00"/>
    <eLiterals name="_11272200" value="121" literal="11-27 22 00"/>
    <eLiterals name="_11272211" value="122" literal="11-27 22 11"/>
    <eLiterals name="_11272500" value="123" literal="11-27 25 00"/>
    <eLiterals name="_11272800" value="124" literal="11-27 28 00"/>
    <eLiterals name="_11273800" value="125" literal="11-27 38 00"/>
    <eLiterals name="_11273811" value="126" literal="11-27 38 11"/>
    <eLiterals name="_11273814" value="127" literal="11-27 38 14"/>
    <eLiterals name="_11273817" value="128" literal="11-27 38 17"/>
    <eLiterals name="_11274200" value="129" literal="11-27 42 00"/>
    <eLiterals name="_11274500" value="130" literal="11-27 45 00"/>
    <eLiterals name="_11275521" value="131" literal="11-27 55 21"/>
    <eLiterals name="_11275522" value="132" literal="11-27 55 22"/>
    <eLiterals name="_11276541" value="133" literal="11-27 65 41"/>
    <eLiterals name="_11290000" value="134" literal="11-29 00 00"/>
    <eLiterals name="_11291200" value="135" literal="11-29 12 00"/>
    <eLiterals name="_1129121111" value="136" literal="11-29 12 11 11"/>
    <eLiterals name="_1129121433" value="137" literal="11-29 12 14 33"/>
    <eLiterals name="_1129121815" value="138" literal="11-29 12 18 15"/>
    <eLiterals name="_1129121817" value="139" literal="11-29 12 18 17"/>
    <eLiterals name="_1129121821" value="140" literal="11-29 12 18 21"/>
    <eLiterals name="_1129121827" value="141" literal="11-29 12 18 27"/>
    <eLiterals name="_1129121831" value="142" literal="11-29 12 18 31"/>
    <eLiterals name="_11292863" value="143" literal="11-29 28 63"/>
    <eLiterals name="_11350000" value="144" literal="11-35 00 00"/>
    <eLiterals name="_11351181" value="145" literal="11-35 11 81"/>
    <eLiterals name="_11351183" value="146" literal="11-35 11 83"/>
    <eLiterals name="_11351186" value="147" literal="11-35 11 86"/>
    <eLiterals name="_11351515" value="148" literal="11-35 15 15"/>
    <eLiterals name="_11351527" value="149" literal="11-35 15 27"/>
    <eLiterals name="_11351931" value="150" literal="11-35 19 31"/>
    <eLiterals name="_11355521" value="151" literal="11-35 55 21"/>
    <eLiterals name="_11355531" value="152" literal="11-35 55 31"/>
    <eLiterals name="_11370000" value="153" literal="11-37 00 00"/>
    <eLiterals name="_11371231" value="154" literal="11-37 12 31"/>
    <eLiterals name="_11371235" value="155" literal="11-37 12 35"/>
    <eLiterals name="_11371239" value="156" literal="11-37 12 39"/>
    <eLiterals name="_11371243" value="157" literal="11-37 12 43"/>
    <eLiterals name="_11373200" value="158" literal="11-37 32 00"/>
    <eLiterals name="_11373211" value="159" literal="11-37 32 11"/>
    <eLiterals name="_11373215" value="160" literal="11-37 32 15"/>
    <eLiterals name="_11373500" value="161" literal="11-37 35 00"/>
    <eLiterals name="_11373900" value="162" literal="11-37 39 00"/>
    <eLiterals name="_11373911" value="163" literal="11-37 39 11"/>
    <eLiterals name="_11373921" value="164" literal="11-37 39 21"/>
    <eLiterals name="_11373931" value="165" literal="11-37 39 31"/>
    <eLiterals name="_11374500" value="166" literal="11-37 45 00"/>
    <eLiterals name="_11374511" value="167" literal="11-37 45 11"/>
    <eLiterals name="_11374515" value="168" literal="11-37 45 15"/>
    <eLiterals name="_11374519" value="169" literal="11-37 45 19"/>
    <eLiterals name="_11374900" value="170" literal="11-37 49 00"/>
    <eLiterals name="_11374911" value="171" literal="11-37 49 11"/>
    <eLiterals name="_11375500" value="172" literal="11-37 55 00"/>
    <eLiterals name="_11375511" value="173" literal="11-37 55 11"/>
    <eLiterals name="_11376500" value="174" literal="11-37 65 00"/>
    <eLiterals name="_11376511" value="175" literal="11-37 65 11"/>
    <eLiterals name="_11376515" value="176" literal="11-37 65 15"/>
    <eLiterals name="_11376519" value="177" literal="11-37 65 19"/>
    <eLiterals name="_11376523" value="178" literal="11-37 65 23"/>
    <eLiterals name="_11376527" value="179" literal="11-37 65 27"/>
    <eLiterals name="_11376531" value="180" literal="11-37 65 31"/>
    <eLiterals name="_11410000" value="181" literal="11-41 00 00"/>
    <eLiterals name="_11420000" value="182" literal="11-42 00 00"/>
    <eLiterals name="_11430000" value="183" literal="11-43 00 00"/>
    <eLiterals name="_11440000" value="184" literal="11-44 00 00"/>
    <eLiterals name="_11441114" value="185" literal="11-44 11 14"/>
    <eLiterals name="_11441117" value="186" literal="11-44 11 17"/>
    <eLiterals name="_11441121" value="187" literal="11-44 11 21"/>
    <eLiterals name="_11441124" value="188" literal="11-44 11 24"/>
    <eLiterals name="_11510000" value="189" literal="11-51 00 00"/>
    <eLiterals name="_11511111" value="190" literal="11-51 11 11"/>
    <eLiterals name="_11511114" value="191" literal="11-51 11 14"/>
    <eLiterals name="_11511117" value="192" literal="11-51 11 17"/>
    <eLiterals name="_11511121" value="193" literal="11-51 11 21"/>
    <eLiterals name="_11511124" value="194" literal="11-51 11 24"/>
    <eLiterals name="_11512100" value="195" literal="11-51 21 00"/>
    <eLiterals name="_11512111" value="196" literal="11-51 21 11"/>
    <eLiterals name="_11512112" value="197" literal="11-51 21 12"/>
    <eLiterals name="_11512114" value="198" literal="11-51 21 14"/>
    <eLiterals name="_11512115" value="199" literal="11-51 21 15"/>
    <eLiterals name="_11512117" value="200" literal="11-51 21 17"/>
    <eLiterals name="_11512121" value="201" literal="11-51 21 21"/>
    <eLiterals name="_11512123" value="202" literal="11-51 21 23"/>
    <eLiterals name="_11512400" value="203" literal="11-51 24 00"/>
    <eLiterals name="_11512411" value="204" literal="11-51 24 11"/>
    <eLiterals name="_11512414" value="205" literal="11-51 24 14"/>
    <eLiterals name="_11512417" value="206" literal="11-51 24 17"/>
    <eLiterals name="_11512711" value="207" literal="11-51 27 11"/>
    <eLiterals name="_11512714" value="208" literal="11-51 27 14"/>
    <eLiterals name="_11512715" value="209" literal="11-51 27 15"/>
    <eLiterals name="_11513100" value="210" literal="11-51 31 00"/>
    <eLiterals name="_11513114" value="211" literal="11-51 31 14"/>
    <eLiterals name="_11514500" value="212" literal="11-51 45 00"/>
    <eLiterals name="_11514511" value="213" literal="11-51 45 11"/>
    <eLiterals name="_11514515" value="214" literal="11-51 45 15"/>
    <eLiterals name="_11514519" value="215" literal="11-51 45 19"/>
    <eLiterals name="_11514523" value="216" literal="11-51 45 23"/>
    <eLiterals name="_11514527" value="217" literal="11-51 45 27"/>
    <eLiterals name="_11514531" value="218" literal="11-51 45 31"/>
    <eLiterals name="_11514535" value="219" literal="11-51 45 35"/>
    <eLiterals name="_11514539" value="220" literal="11-51 45 39"/>
    <eLiterals name="_11514543" value="221" literal="11-51 45 43"/>
    <eLiterals name="_11515313" value="222" literal="11-51 53 13"/>
    <eLiterals name="_11517519" value="223" literal="11-51 75 19"/>
    <eLiterals name="_11900000" value="224" literal="11-90 00 00"/>
    <eLiterals name="_11901100" value="225" literal="11-90 11 00"/>
    <eLiterals name="_11950000" value="226" literal="11-95 00 00"/>
    <eLiterals name="_11951111" value="227" literal="11-95 11 11"/>
    <eLiterals name="_11951115" value="228" literal="11-95 11 15"/>
    <eLiterals name="_11951119" value="229" literal="11-95 11 19"/>
    <eLiterals name="_11951123" value="230" literal="11-95 11 23"/>
    <eLiterals name="_11952333" value="231" literal="11-95 23 33"/>
    <eLiterals name="_11952700" value="232" literal="11-95 27 00"/>
    <eLiterals name="_11953900" value="233" literal="11-95 39 00"/>
    <eLiterals name="_11957100" value="234" literal="11-95 71 00"/>
    <eLiterals name="_11957111" value="235" literal="11-95 71 11"/>
    <eLiterals name="_11957115" value="236" literal="11-95 71 15"/>
    <eLiterals name="_11957119" value="237" literal="11-95 71 19"/>
    <eLiterals name="_11957500" value="238" literal="11-95 75 00"/>
    <eLiterals name="_11958300" value="239" literal="11-95 83 00"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FacilityUsageLevel2CodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageLevel2CodeSimpleType:Object"/>
      <details key="baseType" value="FacilityUsageLevel2CodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacilityUsageLevel2CodeType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FacilityUsageLevel2CodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//FacilityUsageLevel2CodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
