<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_0" nsURI="http://release.niem.gov/niem/codes/dol_soc/3.0/"
    nsPrefix="_0">
  <eAnnotations source="http://release.niem.gov/niem/conformanceTargets/3.0/">
    <details key="conformanceTargets" value="http://reference.niem.gov/niem/specification/naming-and-design-rules/3.0/#ReferenceSchemaDocument"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="OccupationCodeSimpleType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="OccupationCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_111011" literal="11-1011"/>
    <eLiterals name="_111021" value="1" literal="11-1021"/>
    <eLiterals name="_111031" value="2" literal="11-1031"/>
    <eLiterals name="_112011" value="3" literal="11-2011"/>
    <eLiterals name="_112021" value="4" literal="11-2021"/>
    <eLiterals name="_112022" value="5" literal="11-2022"/>
    <eLiterals name="_112031" value="6" literal="11-2031"/>
    <eLiterals name="_113011" value="7" literal="11-3011"/>
    <eLiterals name="_113021" value="8" literal="11-3021"/>
    <eLiterals name="_113031" value="9" literal="11-3031"/>
    <eLiterals name="_113051" value="10" literal="11-3051"/>
    <eLiterals name="_113061" value="11" literal="11-3061"/>
    <eLiterals name="_113071" value="12" literal="11-3071"/>
    <eLiterals name="_113111" value="13" literal="11-3111"/>
    <eLiterals name="_113121" value="14" literal="11-3121"/>
    <eLiterals name="_113131" value="15" literal="11-3131"/>
    <eLiterals name="_119013" value="16" literal="11-9013"/>
    <eLiterals name="_119021" value="17" literal="11-9021"/>
    <eLiterals name="_119031" value="18" literal="11-9031"/>
    <eLiterals name="_119032" value="19" literal="11-9032"/>
    <eLiterals name="_119033" value="20" literal="11-9033"/>
    <eLiterals name="_119039" value="21" literal="11-9039"/>
    <eLiterals name="_119041" value="22" literal="11-9041"/>
    <eLiterals name="_119051" value="23" literal="11-9051"/>
    <eLiterals name="_119061" value="24" literal="11-9061"/>
    <eLiterals name="_119071" value="25" literal="11-9071"/>
    <eLiterals name="_119081" value="26" literal="11-9081"/>
    <eLiterals name="_119111" value="27" literal="11-9111"/>
    <eLiterals name="_119121" value="28" literal="11-9121"/>
    <eLiterals name="_119131" value="29" literal="11-9131"/>
    <eLiterals name="_119141" value="30" literal="11-9141"/>
    <eLiterals name="_119151" value="31" literal="11-9151"/>
    <eLiterals name="_119161" value="32" literal="11-9161"/>
    <eLiterals name="_119199" value="33" literal="11-9199"/>
    <eLiterals name="_131011" value="34" literal="13-1011"/>
    <eLiterals name="_131021" value="35" literal="13-1021"/>
    <eLiterals name="_131022" value="36" literal="13-1022"/>
    <eLiterals name="_131023" value="37" literal="13-1023"/>
    <eLiterals name="_131031" value="38" literal="13-1031"/>
    <eLiterals name="_131032" value="39" literal="13-1032"/>
    <eLiterals name="_131041" value="40" literal="13-1041"/>
    <eLiterals name="_131051" value="41" literal="13-1051"/>
    <eLiterals name="_131071" value="42" literal="13-1071"/>
    <eLiterals name="_131074" value="43" literal="13-1074"/>
    <eLiterals name="_131075" value="44" literal="13-1075"/>
    <eLiterals name="_131081" value="45" literal="13-1081"/>
    <eLiterals name="_131111" value="46" literal="13-1111"/>
    <eLiterals name="_131121" value="47" literal="13-1121"/>
    <eLiterals name="_131131" value="48" literal="13-1131"/>
    <eLiterals name="_131141" value="49" literal="13-1141"/>
    <eLiterals name="_131151" value="50" literal="13-1151"/>
    <eLiterals name="_131161" value="51" literal="13-1161"/>
    <eLiterals name="_131199" value="52" literal="13-1199"/>
    <eLiterals name="_132011" value="53" literal="13-2011"/>
    <eLiterals name="_132021" value="54" literal="13-2021"/>
    <eLiterals name="_132031" value="55" literal="13-2031"/>
    <eLiterals name="_132041" value="56" literal="13-2041"/>
    <eLiterals name="_132051" value="57" literal="13-2051"/>
    <eLiterals name="_132052" value="58" literal="13-2052"/>
    <eLiterals name="_132053" value="59" literal="13-2053"/>
    <eLiterals name="_132061" value="60" literal="13-2061"/>
    <eLiterals name="_132071" value="61" literal="13-2071"/>
    <eLiterals name="_132072" value="62" literal="13-2072"/>
    <eLiterals name="_132081" value="63" literal="13-2081"/>
    <eLiterals name="_132082" value="64" literal="13-2082"/>
    <eLiterals name="_132099" value="65" literal="13-2099"/>
    <eLiterals name="_151111" value="66" literal="15-1111"/>
    <eLiterals name="_151121" value="67" literal="15-1121"/>
    <eLiterals name="_151122" value="68" literal="15-1122"/>
    <eLiterals name="_151131" value="69" literal="15-1131"/>
    <eLiterals name="_151132" value="70" literal="15-1132"/>
    <eLiterals name="_151133" value="71" literal="15-1133"/>
    <eLiterals name="_151134" value="72" literal="15-1134"/>
    <eLiterals name="_151141" value="73" literal="15-1141"/>
    <eLiterals name="_151142" value="74" literal="15-1142"/>
    <eLiterals name="_151143" value="75" literal="15-1143"/>
    <eLiterals name="_151151" value="76" literal="15-1151"/>
    <eLiterals name="_151152" value="77" literal="15-1152"/>
    <eLiterals name="_151199" value="78" literal="15-1199"/>
    <eLiterals name="_152011" value="79" literal="15-2011"/>
    <eLiterals name="_152021" value="80" literal="15-2021"/>
    <eLiterals name="_152031" value="81" literal="15-2031"/>
    <eLiterals name="_152041" value="82" literal="15-2041"/>
    <eLiterals name="_152091" value="83" literal="15-2091"/>
    <eLiterals name="_152099" value="84" literal="15-2099"/>
    <eLiterals name="_171011" value="85" literal="17-1011"/>
    <eLiterals name="_171012" value="86" literal="17-1012"/>
    <eLiterals name="_171021" value="87" literal="17-1021"/>
    <eLiterals name="_171022" value="88" literal="17-1022"/>
    <eLiterals name="_172011" value="89" literal="17-2011"/>
    <eLiterals name="_172021" value="90" literal="17-2021"/>
    <eLiterals name="_172031" value="91" literal="17-2031"/>
    <eLiterals name="_172041" value="92" literal="17-2041"/>
    <eLiterals name="_172051" value="93" literal="17-2051"/>
    <eLiterals name="_172061" value="94" literal="17-2061"/>
    <eLiterals name="_172071" value="95" literal="17-2071"/>
    <eLiterals name="_172072" value="96" literal="17-2072"/>
    <eLiterals name="_172081" value="97" literal="17-2081"/>
    <eLiterals name="_172111" value="98" literal="17-2111"/>
    <eLiterals name="_172112" value="99" literal="17-2112"/>
    <eLiterals name="_172121" value="100" literal="17-2121"/>
    <eLiterals name="_172131" value="101" literal="17-2131"/>
    <eLiterals name="_172141" value="102" literal="17-2141"/>
    <eLiterals name="_172151" value="103" literal="17-2151"/>
    <eLiterals name="_172161" value="104" literal="17-2161"/>
    <eLiterals name="_172171" value="105" literal="17-2171"/>
    <eLiterals name="_172199" value="106" literal="17-2199"/>
    <eLiterals name="_173011" value="107" literal="17-3011"/>
    <eLiterals name="_173012" value="108" literal="17-3012"/>
    <eLiterals name="_173013" value="109" literal="17-3013"/>
    <eLiterals name="_173019" value="110" literal="17-3019"/>
    <eLiterals name="_173021" value="111" literal="17-3021"/>
    <eLiterals name="_173022" value="112" literal="17-3022"/>
    <eLiterals name="_173023" value="113" literal="17-3023"/>
    <eLiterals name="_173024" value="114" literal="17-3024"/>
    <eLiterals name="_173025" value="115" literal="17-3025"/>
    <eLiterals name="_173026" value="116" literal="17-3026"/>
    <eLiterals name="_173027" value="117" literal="17-3027"/>
    <eLiterals name="_173029" value="118" literal="17-3029"/>
    <eLiterals name="_173031" value="119" literal="17-3031"/>
    <eLiterals name="_191011" value="120" literal="19-1011"/>
    <eLiterals name="_191012" value="121" literal="19-1012"/>
    <eLiterals name="_191013" value="122" literal="19-1013"/>
    <eLiterals name="_191021" value="123" literal="19-1021"/>
    <eLiterals name="_191022" value="124" literal="19-1022"/>
    <eLiterals name="_191023" value="125" literal="19-1023"/>
    <eLiterals name="_191029" value="126" literal="19-1029"/>
    <eLiterals name="_191031" value="127" literal="19-1031"/>
    <eLiterals name="_191032" value="128" literal="19-1032"/>
    <eLiterals name="_191041" value="129" literal="19-1041"/>
    <eLiterals name="_191042" value="130" literal="19-1042"/>
    <eLiterals name="_191099" value="131" literal="19-1099"/>
    <eLiterals name="_192011" value="132" literal="19-2011"/>
    <eLiterals name="_192012" value="133" literal="19-2012"/>
    <eLiterals name="_192021" value="134" literal="19-2021"/>
    <eLiterals name="_192031" value="135" literal="19-2031"/>
    <eLiterals name="_192032" value="136" literal="19-2032"/>
    <eLiterals name="_192041" value="137" literal="19-2041"/>
    <eLiterals name="_192042" value="138" literal="19-2042"/>
    <eLiterals name="_192043" value="139" literal="19-2043"/>
    <eLiterals name="_192099" value="140" literal="19-2099"/>
    <eLiterals name="_193011" value="141" literal="19-3011"/>
    <eLiterals name="_193022" value="142" literal="19-3022"/>
    <eLiterals name="_193031" value="143" literal="19-3031"/>
    <eLiterals name="_193032" value="144" literal="19-3032"/>
    <eLiterals name="_193039" value="145" literal="19-3039"/>
    <eLiterals name="_193041" value="146" literal="19-3041"/>
    <eLiterals name="_193051" value="147" literal="19-3051"/>
    <eLiterals name="_193091" value="148" literal="19-3091"/>
    <eLiterals name="_193092" value="149" literal="19-3092"/>
    <eLiterals name="_193093" value="150" literal="19-3093"/>
    <eLiterals name="_193094" value="151" literal="19-3094"/>
    <eLiterals name="_193099" value="152" literal="19-3099"/>
    <eLiterals name="_194011" value="153" literal="19-4011"/>
    <eLiterals name="_194021" value="154" literal="19-4021"/>
    <eLiterals name="_194031" value="155" literal="19-4031"/>
    <eLiterals name="_194041" value="156" literal="19-4041"/>
    <eLiterals name="_194051" value="157" literal="19-4051"/>
    <eLiterals name="_194061" value="158" literal="19-4061"/>
    <eLiterals name="_194091" value="159" literal="19-4091"/>
    <eLiterals name="_194092" value="160" literal="19-4092"/>
    <eLiterals name="_194093" value="161" literal="19-4093"/>
    <eLiterals name="_194099" value="162" literal="19-4099"/>
    <eLiterals name="_211011" value="163" literal="21-1011"/>
    <eLiterals name="_211012" value="164" literal="21-1012"/>
    <eLiterals name="_211013" value="165" literal="21-1013"/>
    <eLiterals name="_211014" value="166" literal="21-1014"/>
    <eLiterals name="_211015" value="167" literal="21-1015"/>
    <eLiterals name="_211019" value="168" literal="21-1019"/>
    <eLiterals name="_211021" value="169" literal="21-1021"/>
    <eLiterals name="_211022" value="170" literal="21-1022"/>
    <eLiterals name="_211023" value="171" literal="21-1023"/>
    <eLiterals name="_211029" value="172" literal="21-1029"/>
    <eLiterals name="_211091" value="173" literal="21-1091"/>
    <eLiterals name="_211092" value="174" literal="21-1092"/>
    <eLiterals name="_211093" value="175" literal="21-1093"/>
    <eLiterals name="_211094" value="176" literal="21-1094"/>
    <eLiterals name="_211099" value="177" literal="21-1099"/>
    <eLiterals name="_212011" value="178" literal="21-2011"/>
    <eLiterals name="_212021" value="179" literal="21-2021"/>
    <eLiterals name="_212099" value="180" literal="21-2099"/>
    <eLiterals name="_231011" value="181" literal="23-1011"/>
    <eLiterals name="_231012" value="182" literal="23-1012"/>
    <eLiterals name="_231021" value="183" literal="23-1021"/>
    <eLiterals name="_231022" value="184" literal="23-1022"/>
    <eLiterals name="_231023" value="185" literal="23-1023"/>
    <eLiterals name="_232011" value="186" literal="23-2011"/>
    <eLiterals name="_232091" value="187" literal="23-2091"/>
    <eLiterals name="_232093" value="188" literal="23-2093"/>
    <eLiterals name="_232099" value="189" literal="23-2099"/>
    <eLiterals name="_251011" value="190" literal="25-1011"/>
    <eLiterals name="_251021" value="191" literal="25-1021"/>
    <eLiterals name="_251022" value="192" literal="25-1022"/>
    <eLiterals name="_251031" value="193" literal="25-1031"/>
    <eLiterals name="_251032" value="194" literal="25-1032"/>
    <eLiterals name="_251041" value="195" literal="25-1041"/>
    <eLiterals name="_251042" value="196" literal="25-1042"/>
    <eLiterals name="_251043" value="197" literal="25-1043"/>
    <eLiterals name="_251051" value="198" literal="25-1051"/>
    <eLiterals name="_251052" value="199" literal="25-1052"/>
    <eLiterals name="_251053" value="200" literal="25-1053"/>
    <eLiterals name="_251054" value="201" literal="25-1054"/>
    <eLiterals name="_251061" value="202" literal="25-1061"/>
    <eLiterals name="_251062" value="203" literal="25-1062"/>
    <eLiterals name="_251063" value="204" literal="25-1063"/>
    <eLiterals name="_251064" value="205" literal="25-1064"/>
    <eLiterals name="_251065" value="206" literal="25-1065"/>
    <eLiterals name="_251066" value="207" literal="25-1066"/>
    <eLiterals name="_251067" value="208" literal="25-1067"/>
    <eLiterals name="_251069" value="209" literal="25-1069"/>
    <eLiterals name="_251071" value="210" literal="25-1071"/>
    <eLiterals name="_251072" value="211" literal="25-1072"/>
    <eLiterals name="_251081" value="212" literal="25-1081"/>
    <eLiterals name="_251082" value="213" literal="25-1082"/>
    <eLiterals name="_251111" value="214" literal="25-1111"/>
    <eLiterals name="_251112" value="215" literal="25-1112"/>
    <eLiterals name="_251113" value="216" literal="25-1113"/>
    <eLiterals name="_251121" value="217" literal="25-1121"/>
    <eLiterals name="_251122" value="218" literal="25-1122"/>
    <eLiterals name="_251123" value="219" literal="25-1123"/>
    <eLiterals name="_251124" value="220" literal="25-1124"/>
    <eLiterals name="_251125" value="221" literal="25-1125"/>
    <eLiterals name="_251126" value="222" literal="25-1126"/>
    <eLiterals name="_251191" value="223" literal="25-1191"/>
    <eLiterals name="_251192" value="224" literal="25-1192"/>
    <eLiterals name="_251193" value="225" literal="25-1193"/>
    <eLiterals name="_251194" value="226" literal="25-1194"/>
    <eLiterals name="_251199" value="227" literal="25-1199"/>
    <eLiterals name="_252011" value="228" literal="25-2011"/>
    <eLiterals name="_252012" value="229" literal="25-2012"/>
    <eLiterals name="_252021" value="230" literal="25-2021"/>
    <eLiterals name="_252022" value="231" literal="25-2022"/>
    <eLiterals name="_252023" value="232" literal="25-2023"/>
    <eLiterals name="_252031" value="233" literal="25-2031"/>
    <eLiterals name="_252032" value="234" literal="25-2032"/>
    <eLiterals name="_252051" value="235" literal="25-2051"/>
    <eLiterals name="_252052" value="236" literal="25-2052"/>
    <eLiterals name="_252053" value="237" literal="25-2053"/>
    <eLiterals name="_252054" value="238" literal="25-2054"/>
    <eLiterals name="_252059" value="239" literal="25-2059"/>
    <eLiterals name="_253011" value="240" literal="25-3011"/>
    <eLiterals name="_253021" value="241" literal="25-3021"/>
    <eLiterals name="_253099" value="242" literal="25-3099"/>
    <eLiterals name="_254011" value="243" literal="25-4011"/>
    <eLiterals name="_254012" value="244" literal="25-4012"/>
    <eLiterals name="_254013" value="245" literal="25-4013"/>
    <eLiterals name="_254021" value="246" literal="25-4021"/>
    <eLiterals name="_254031" value="247" literal="25-4031"/>
    <eLiterals name="_259011" value="248" literal="25-9011"/>
    <eLiterals name="_259021" value="249" literal="25-9021"/>
    <eLiterals name="_259031" value="250" literal="25-9031"/>
    <eLiterals name="_259041" value="251" literal="25-9041"/>
    <eLiterals name="_259099" value="252" literal="25-9099"/>
    <eLiterals name="_271011" value="253" literal="27-1011"/>
    <eLiterals name="_271012" value="254" literal="27-1012"/>
    <eLiterals name="_271013" value="255" literal="27-1013"/>
    <eLiterals name="_271014" value="256" literal="27-1014"/>
    <eLiterals name="_271019" value="257" literal="27-1019"/>
    <eLiterals name="_271021" value="258" literal="27-1021"/>
    <eLiterals name="_271022" value="259" literal="27-1022"/>
    <eLiterals name="_271023" value="260" literal="27-1023"/>
    <eLiterals name="_271024" value="261" literal="27-1024"/>
    <eLiterals name="_271025" value="262" literal="27-1025"/>
    <eLiterals name="_271026" value="263" literal="27-1026"/>
    <eLiterals name="_271027" value="264" literal="27-1027"/>
    <eLiterals name="_271029" value="265" literal="27-1029"/>
    <eLiterals name="_272011" value="266" literal="27-2011"/>
    <eLiterals name="_272012" value="267" literal="27-2012"/>
    <eLiterals name="_272021" value="268" literal="27-2021"/>
    <eLiterals name="_272022" value="269" literal="27-2022"/>
    <eLiterals name="_272023" value="270" literal="27-2023"/>
    <eLiterals name="_272031" value="271" literal="27-2031"/>
    <eLiterals name="_272032" value="272" literal="27-2032"/>
    <eLiterals name="_272041" value="273" literal="27-2041"/>
    <eLiterals name="_272042" value="274" literal="27-2042"/>
    <eLiterals name="_272099" value="275" literal="27-2099"/>
    <eLiterals name="_273011" value="276" literal="27-3011"/>
    <eLiterals name="_273012" value="277" literal="27-3012"/>
    <eLiterals name="_273021" value="278" literal="27-3021"/>
    <eLiterals name="_273022" value="279" literal="27-3022"/>
    <eLiterals name="_273031" value="280" literal="27-3031"/>
    <eLiterals name="_273041" value="281" literal="27-3041"/>
    <eLiterals name="_273042" value="282" literal="27-3042"/>
    <eLiterals name="_273043" value="283" literal="27-3043"/>
    <eLiterals name="_273091" value="284" literal="27-3091"/>
    <eLiterals name="_273099" value="285" literal="27-3099"/>
    <eLiterals name="_274011" value="286" literal="27-4011"/>
    <eLiterals name="_274012" value="287" literal="27-4012"/>
    <eLiterals name="_274013" value="288" literal="27-4013"/>
    <eLiterals name="_274014" value="289" literal="27-4014"/>
    <eLiterals name="_274021" value="290" literal="27-4021"/>
    <eLiterals name="_274031" value="291" literal="27-4031"/>
    <eLiterals name="_274032" value="292" literal="27-4032"/>
    <eLiterals name="_274099" value="293" literal="27-4099"/>
    <eLiterals name="_291011" value="294" literal="29-1011"/>
    <eLiterals name="_291021" value="295" literal="29-1021"/>
    <eLiterals name="_291022" value="296" literal="29-1022"/>
    <eLiterals name="_291023" value="297" literal="29-1023"/>
    <eLiterals name="_291024" value="298" literal="29-1024"/>
    <eLiterals name="_291029" value="299" literal="29-1029"/>
    <eLiterals name="_291031" value="300" literal="29-1031"/>
    <eLiterals name="_291041" value="301" literal="29-1041"/>
    <eLiterals name="_291051" value="302" literal="29-1051"/>
    <eLiterals name="_291061" value="303" literal="29-1061"/>
    <eLiterals name="_291062" value="304" literal="29-1062"/>
    <eLiterals name="_291063" value="305" literal="29-1063"/>
    <eLiterals name="_291064" value="306" literal="29-1064"/>
    <eLiterals name="_291065" value="307" literal="29-1065"/>
    <eLiterals name="_291066" value="308" literal="29-1066"/>
    <eLiterals name="_291067" value="309" literal="29-1067"/>
    <eLiterals name="_291069" value="310" literal="29-1069"/>
    <eLiterals name="_291071" value="311" literal="29-1071"/>
    <eLiterals name="_291081" value="312" literal="29-1081"/>
    <eLiterals name="_291122" value="313" literal="29-1122"/>
    <eLiterals name="_291123" value="314" literal="29-1123"/>
    <eLiterals name="_291124" value="315" literal="29-1124"/>
    <eLiterals name="_291125" value="316" literal="29-1125"/>
    <eLiterals name="_291126" value="317" literal="29-1126"/>
    <eLiterals name="_291127" value="318" literal="29-1127"/>
    <eLiterals name="_291128" value="319" literal="29-1128"/>
    <eLiterals name="_291129" value="320" literal="29-1129"/>
    <eLiterals name="_291131" value="321" literal="29-1131"/>
    <eLiterals name="_291141" value="322" literal="29-1141"/>
    <eLiterals name="_291151" value="323" literal="29-1151"/>
    <eLiterals name="_291161" value="324" literal="29-1161"/>
    <eLiterals name="_291171" value="325" literal="29-1171"/>
    <eLiterals name="_291181" value="326" literal="29-1181"/>
    <eLiterals name="_291199" value="327" literal="29-1199"/>
    <eLiterals name="_292011" value="328" literal="29-2011"/>
    <eLiterals name="_292012" value="329" literal="29-2012"/>
    <eLiterals name="_292021" value="330" literal="29-2021"/>
    <eLiterals name="_292031" value="331" literal="29-2031"/>
    <eLiterals name="_292032" value="332" literal="29-2032"/>
    <eLiterals name="_292033" value="333" literal="29-2033"/>
    <eLiterals name="_292034" value="334" literal="29-2034"/>
    <eLiterals name="_292035" value="335" literal="29-2035"/>
    <eLiterals name="_292041" value="336" literal="29-2041"/>
    <eLiterals name="_292051" value="337" literal="29-2051"/>
    <eLiterals name="_292052" value="338" literal="29-2052"/>
    <eLiterals name="_292053" value="339" literal="29-2053"/>
    <eLiterals name="_292054" value="340" literal="29-2054"/>
    <eLiterals name="_292055" value="341" literal="29-2055"/>
    <eLiterals name="_292056" value="342" literal="29-2056"/>
    <eLiterals name="_292057" value="343" literal="29-2057"/>
    <eLiterals name="_292061" value="344" literal="29-2061"/>
    <eLiterals name="_292071" value="345" literal="29-2071"/>
    <eLiterals name="_292081" value="346" literal="29-2081"/>
    <eLiterals name="_292091" value="347" literal="29-2091"/>
    <eLiterals name="_292092" value="348" literal="29-2092"/>
    <eLiterals name="_292099" value="349" literal="29-2099"/>
    <eLiterals name="_299011" value="350" literal="29-9011"/>
    <eLiterals name="_299012" value="351" literal="29-9012"/>
    <eLiterals name="_299091" value="352" literal="29-9091"/>
    <eLiterals name="_299092" value="353" literal="29-9092"/>
    <eLiterals name="_299099" value="354" literal="29-9099"/>
    <eLiterals name="_311011" value="355" literal="31-1011"/>
    <eLiterals name="_311013" value="356" literal="31-1013"/>
    <eLiterals name="_311014" value="357" literal="31-1014"/>
    <eLiterals name="_311015" value="358" literal="31-1015"/>
    <eLiterals name="_312011" value="359" literal="31-2011"/>
    <eLiterals name="_312012" value="360" literal="31-2012"/>
    <eLiterals name="_312021" value="361" literal="31-2021"/>
    <eLiterals name="_312022" value="362" literal="31-2022"/>
    <eLiterals name="_319011" value="363" literal="31-9011"/>
    <eLiterals name="_319091" value="364" literal="31-9091"/>
    <eLiterals name="_319092" value="365" literal="31-9092"/>
    <eLiterals name="_319093" value="366" literal="31-9093"/>
    <eLiterals name="_319094" value="367" literal="31-9094"/>
    <eLiterals name="_319095" value="368" literal="31-9095"/>
    <eLiterals name="_319096" value="369" literal="31-9096"/>
    <eLiterals name="_319097" value="370" literal="31-9097"/>
    <eLiterals name="_319099" value="371" literal="31-9099"/>
    <eLiterals name="_331011" value="372" literal="33-1011"/>
    <eLiterals name="_331012" value="373" literal="33-1012"/>
    <eLiterals name="_331021" value="374" literal="33-1021"/>
    <eLiterals name="_331099" value="375" literal="33-1099"/>
    <eLiterals name="_332011" value="376" literal="33-2011"/>
    <eLiterals name="_332021" value="377" literal="33-2021"/>
    <eLiterals name="_332022" value="378" literal="33-2022"/>
    <eLiterals name="_333011" value="379" literal="33-3011"/>
    <eLiterals name="_333012" value="380" literal="33-3012"/>
    <eLiterals name="_333021" value="381" literal="33-3021"/>
    <eLiterals name="_333031" value="382" literal="33-3031"/>
    <eLiterals name="_333041" value="383" literal="33-3041"/>
    <eLiterals name="_333051" value="384" literal="33-3051"/>
    <eLiterals name="_333052" value="385" literal="33-3052"/>
    <eLiterals name="_339011" value="386" literal="33-9011"/>
    <eLiterals name="_339021" value="387" literal="33-9021"/>
    <eLiterals name="_339031" value="388" literal="33-9031"/>
    <eLiterals name="_339032" value="389" literal="33-9032"/>
    <eLiterals name="_339091" value="390" literal="33-9091"/>
    <eLiterals name="_339092" value="391" literal="33-9092"/>
    <eLiterals name="_339093" value="392" literal="33-9093"/>
    <eLiterals name="_339099" value="393" literal="33-9099"/>
    <eLiterals name="_351011" value="394" literal="35-1011"/>
    <eLiterals name="_351012" value="395" literal="35-1012"/>
    <eLiterals name="_352011" value="396" literal="35-2011"/>
    <eLiterals name="_352012" value="397" literal="35-2012"/>
    <eLiterals name="_352013" value="398" literal="35-2013"/>
    <eLiterals name="_352014" value="399" literal="35-2014"/>
    <eLiterals name="_352015" value="400" literal="35-2015"/>
    <eLiterals name="_352019" value="401" literal="35-2019"/>
    <eLiterals name="_352021" value="402" literal="35-2021"/>
    <eLiterals name="_353011" value="403" literal="35-3011"/>
    <eLiterals name="_353021" value="404" literal="35-3021"/>
    <eLiterals name="_353022" value="405" literal="35-3022"/>
    <eLiterals name="_353031" value="406" literal="35-3031"/>
    <eLiterals name="_353041" value="407" literal="35-3041"/>
    <eLiterals name="_359011" value="408" literal="35-9011"/>
    <eLiterals name="_359021" value="409" literal="35-9021"/>
    <eLiterals name="_359031" value="410" literal="35-9031"/>
    <eLiterals name="_359099" value="411" literal="35-9099"/>
    <eLiterals name="_371011" value="412" literal="37-1011"/>
    <eLiterals name="_371012" value="413" literal="37-1012"/>
    <eLiterals name="_372011" value="414" literal="37-2011"/>
    <eLiterals name="_372012" value="415" literal="37-2012"/>
    <eLiterals name="_372019" value="416" literal="37-2019"/>
    <eLiterals name="_372021" value="417" literal="37-2021"/>
    <eLiterals name="_373011" value="418" literal="37-3011"/>
    <eLiterals name="_373012" value="419" literal="37-3012"/>
    <eLiterals name="_373013" value="420" literal="37-3013"/>
    <eLiterals name="_373019" value="421" literal="37-3019"/>
    <eLiterals name="_391011" value="422" literal="39-1011"/>
    <eLiterals name="_391012" value="423" literal="39-1012"/>
    <eLiterals name="_391021" value="424" literal="39-1021"/>
    <eLiterals name="_392011" value="425" literal="39-2011"/>
    <eLiterals name="_392021" value="426" literal="39-2021"/>
    <eLiterals name="_393011" value="427" literal="39-3011"/>
    <eLiterals name="_393012" value="428" literal="39-3012"/>
    <eLiterals name="_393019" value="429" literal="39-3019"/>
    <eLiterals name="_393021" value="430" literal="39-3021"/>
    <eLiterals name="_393031" value="431" literal="39-3031"/>
    <eLiterals name="_393091" value="432" literal="39-3091"/>
    <eLiterals name="_393092" value="433" literal="39-3092"/>
    <eLiterals name="_393093" value="434" literal="39-3093"/>
    <eLiterals name="_393099" value="435" literal="39-3099"/>
    <eLiterals name="_394011" value="436" literal="39-4011"/>
    <eLiterals name="_394021" value="437" literal="39-4021"/>
    <eLiterals name="_394031" value="438" literal="39-4031"/>
    <eLiterals name="_395011" value="439" literal="39-5011"/>
    <eLiterals name="_395012" value="440" literal="39-5012"/>
    <eLiterals name="_395091" value="441" literal="39-5091"/>
    <eLiterals name="_395092" value="442" literal="39-5092"/>
    <eLiterals name="_395093" value="443" literal="39-5093"/>
    <eLiterals name="_395094" value="444" literal="39-5094"/>
    <eLiterals name="_396011" value="445" literal="39-6011"/>
    <eLiterals name="_396012" value="446" literal="39-6012"/>
    <eLiterals name="_397011" value="447" literal="39-7011"/>
    <eLiterals name="_397012" value="448" literal="39-7012"/>
    <eLiterals name="_399011" value="449" literal="39-9011"/>
    <eLiterals name="_399021" value="450" literal="39-9021"/>
    <eLiterals name="_399031" value="451" literal="39-9031"/>
    <eLiterals name="_399032" value="452" literal="39-9032"/>
    <eLiterals name="_399041" value="453" literal="39-9041"/>
    <eLiterals name="_399099" value="454" literal="39-9099"/>
    <eLiterals name="_411011" value="455" literal="41-1011"/>
    <eLiterals name="_411012" value="456" literal="41-1012"/>
    <eLiterals name="_412011" value="457" literal="41-2011"/>
    <eLiterals name="_412012" value="458" literal="41-2012"/>
    <eLiterals name="_412021" value="459" literal="41-2021"/>
    <eLiterals name="_412022" value="460" literal="41-2022"/>
    <eLiterals name="_412031" value="461" literal="41-2031"/>
    <eLiterals name="_413011" value="462" literal="41-3011"/>
    <eLiterals name="_413021" value="463" literal="41-3021"/>
    <eLiterals name="_413031" value="464" literal="41-3031"/>
    <eLiterals name="_413041" value="465" literal="41-3041"/>
    <eLiterals name="_413099" value="466" literal="41-3099"/>
    <eLiterals name="_414011" value="467" literal="41-4011"/>
    <eLiterals name="_414012" value="468" literal="41-4012"/>
    <eLiterals name="_419011" value="469" literal="41-9011"/>
    <eLiterals name="_419012" value="470" literal="41-9012"/>
    <eLiterals name="_419021" value="471" literal="41-9021"/>
    <eLiterals name="_419022" value="472" literal="41-9022"/>
    <eLiterals name="_419031" value="473" literal="41-9031"/>
    <eLiterals name="_419041" value="474" literal="41-9041"/>
    <eLiterals name="_419091" value="475" literal="41-9091"/>
    <eLiterals name="_419099" value="476" literal="41-9099"/>
    <eLiterals name="_431011" value="477" literal="43-1011"/>
    <eLiterals name="_432011" value="478" literal="43-2011"/>
    <eLiterals name="_432021" value="479" literal="43-2021"/>
    <eLiterals name="_432099" value="480" literal="43-2099"/>
    <eLiterals name="_433011" value="481" literal="43-3011"/>
    <eLiterals name="_433021" value="482" literal="43-3021"/>
    <eLiterals name="_433031" value="483" literal="43-3031"/>
    <eLiterals name="_433041" value="484" literal="43-3041"/>
    <eLiterals name="_433051" value="485" literal="43-3051"/>
    <eLiterals name="_433061" value="486" literal="43-3061"/>
    <eLiterals name="_433071" value="487" literal="43-3071"/>
    <eLiterals name="_433099" value="488" literal="43-3099"/>
    <eLiterals name="_434011" value="489" literal="43-4011"/>
    <eLiterals name="_434021" value="490" literal="43-4021"/>
    <eLiterals name="_434031" value="491" literal="43-4031"/>
    <eLiterals name="_434041" value="492" literal="43-4041"/>
    <eLiterals name="_434051" value="493" literal="43-4051"/>
    <eLiterals name="_434061" value="494" literal="43-4061"/>
    <eLiterals name="_434071" value="495" literal="43-4071"/>
    <eLiterals name="_434081" value="496" literal="43-4081"/>
    <eLiterals name="_434111" value="497" literal="43-4111"/>
    <eLiterals name="_434121" value="498" literal="43-4121"/>
    <eLiterals name="_434131" value="499" literal="43-4131"/>
    <eLiterals name="_434141" value="500" literal="43-4141"/>
    <eLiterals name="_434151" value="501" literal="43-4151"/>
    <eLiterals name="_434161" value="502" literal="43-4161"/>
    <eLiterals name="_434171" value="503" literal="43-4171"/>
    <eLiterals name="_434181" value="504" literal="43-4181"/>
    <eLiterals name="_434199" value="505" literal="43-4199"/>
    <eLiterals name="_435011" value="506" literal="43-5011"/>
    <eLiterals name="_435021" value="507" literal="43-5021"/>
    <eLiterals name="_435031" value="508" literal="43-5031"/>
    <eLiterals name="_435032" value="509" literal="43-5032"/>
    <eLiterals name="_435041" value="510" literal="43-5041"/>
    <eLiterals name="_435051" value="511" literal="43-5051"/>
    <eLiterals name="_435052" value="512" literal="43-5052"/>
    <eLiterals name="_435053" value="513" literal="43-5053"/>
    <eLiterals name="_435061" value="514" literal="43-5061"/>
    <eLiterals name="_435071" value="515" literal="43-5071"/>
    <eLiterals name="_435081" value="516" literal="43-5081"/>
    <eLiterals name="_435111" value="517" literal="43-5111"/>
    <eLiterals name="_436011" value="518" literal="43-6011"/>
    <eLiterals name="_436012" value="519" literal="43-6012"/>
    <eLiterals name="_436013" value="520" literal="43-6013"/>
    <eLiterals name="_436014" value="521" literal="43-6014"/>
    <eLiterals name="_439011" value="522" literal="43-9011"/>
    <eLiterals name="_439021" value="523" literal="43-9021"/>
    <eLiterals name="_439022" value="524" literal="43-9022"/>
    <eLiterals name="_439031" value="525" literal="43-9031"/>
    <eLiterals name="_439041" value="526" literal="43-9041"/>
    <eLiterals name="_439051" value="527" literal="43-9051"/>
    <eLiterals name="_439061" value="528" literal="43-9061"/>
    <eLiterals name="_439071" value="529" literal="43-9071"/>
    <eLiterals name="_439081" value="530" literal="43-9081"/>
    <eLiterals name="_439111" value="531" literal="43-9111"/>
    <eLiterals name="_439199" value="532" literal="43-9199"/>
    <eLiterals name="_451011" value="533" literal="45-1011"/>
    <eLiterals name="_452011" value="534" literal="45-2011"/>
    <eLiterals name="_452021" value="535" literal="45-2021"/>
    <eLiterals name="_452041" value="536" literal="45-2041"/>
    <eLiterals name="_452091" value="537" literal="45-2091"/>
    <eLiterals name="_452092" value="538" literal="45-2092"/>
    <eLiterals name="_452093" value="539" literal="45-2093"/>
    <eLiterals name="_452099" value="540" literal="45-2099"/>
    <eLiterals name="_453011" value="541" literal="45-3011"/>
    <eLiterals name="_453021" value="542" literal="45-3021"/>
    <eLiterals name="_454011" value="543" literal="45-4011"/>
    <eLiterals name="_454021" value="544" literal="45-4021"/>
    <eLiterals name="_454022" value="545" literal="45-4022"/>
    <eLiterals name="_454023" value="546" literal="45-4023"/>
    <eLiterals name="_454029" value="547" literal="45-4029"/>
    <eLiterals name="_471011" value="548" literal="47-1011"/>
    <eLiterals name="_472011" value="549" literal="47-2011"/>
    <eLiterals name="_472021" value="550" literal="47-2021"/>
    <eLiterals name="_472022" value="551" literal="47-2022"/>
    <eLiterals name="_472031" value="552" literal="47-2031"/>
    <eLiterals name="_472041" value="553" literal="47-2041"/>
    <eLiterals name="_472042" value="554" literal="47-2042"/>
    <eLiterals name="_472043" value="555" literal="47-2043"/>
    <eLiterals name="_472044" value="556" literal="47-2044"/>
    <eLiterals name="_472051" value="557" literal="47-2051"/>
    <eLiterals name="_472053" value="558" literal="47-2053"/>
    <eLiterals name="_472061" value="559" literal="47-2061"/>
    <eLiterals name="_472071" value="560" literal="47-2071"/>
    <eLiterals name="_472072" value="561" literal="47-2072"/>
    <eLiterals name="_472073" value="562" literal="47-2073"/>
    <eLiterals name="_472081" value="563" literal="47-2081"/>
    <eLiterals name="_472082" value="564" literal="47-2082"/>
    <eLiterals name="_472111" value="565" literal="47-2111"/>
    <eLiterals name="_472121" value="566" literal="47-2121"/>
    <eLiterals name="_472131" value="567" literal="47-2131"/>
    <eLiterals name="_472132" value="568" literal="47-2132"/>
    <eLiterals name="_472141" value="569" literal="47-2141"/>
    <eLiterals name="_472142" value="570" literal="47-2142"/>
    <eLiterals name="_472151" value="571" literal="47-2151"/>
    <eLiterals name="_472152" value="572" literal="47-2152"/>
    <eLiterals name="_472161" value="573" literal="47-2161"/>
    <eLiterals name="_472171" value="574" literal="47-2171"/>
    <eLiterals name="_472181" value="575" literal="47-2181"/>
    <eLiterals name="_472211" value="576" literal="47-2211"/>
    <eLiterals name="_472221" value="577" literal="47-2221"/>
    <eLiterals name="_472231" value="578" literal="47-2231"/>
    <eLiterals name="_473011" value="579" literal="47-3011"/>
    <eLiterals name="_473012" value="580" literal="47-3012"/>
    <eLiterals name="_473013" value="581" literal="47-3013"/>
    <eLiterals name="_473014" value="582" literal="47-3014"/>
    <eLiterals name="_473015" value="583" literal="47-3015"/>
    <eLiterals name="_473016" value="584" literal="47-3016"/>
    <eLiterals name="_473019" value="585" literal="47-3019"/>
    <eLiterals name="_474011" value="586" literal="47-4011"/>
    <eLiterals name="_474021" value="587" literal="47-4021"/>
    <eLiterals name="_474031" value="588" literal="47-4031"/>
    <eLiterals name="_474041" value="589" literal="47-4041"/>
    <eLiterals name="_474051" value="590" literal="47-4051"/>
    <eLiterals name="_474061" value="591" literal="47-4061"/>
    <eLiterals name="_474071" value="592" literal="47-4071"/>
    <eLiterals name="_474091" value="593" literal="47-4091"/>
    <eLiterals name="_474099" value="594" literal="47-4099"/>
    <eLiterals name="_475011" value="595" literal="47-5011"/>
    <eLiterals name="_475012" value="596" literal="47-5012"/>
    <eLiterals name="_475013" value="597" literal="47-5013"/>
    <eLiterals name="_475021" value="598" literal="47-5021"/>
    <eLiterals name="_475031" value="599" literal="47-5031"/>
    <eLiterals name="_475041" value="600" literal="47-5041"/>
    <eLiterals name="_475042" value="601" literal="47-5042"/>
    <eLiterals name="_475049" value="602" literal="47-5049"/>
    <eLiterals name="_475051" value="603" literal="47-5051"/>
    <eLiterals name="_475061" value="604" literal="47-5061"/>
    <eLiterals name="_475071" value="605" literal="47-5071"/>
    <eLiterals name="_475081" value="606" literal="47-5081"/>
    <eLiterals name="_475099" value="607" literal="47-5099"/>
    <eLiterals name="_491011" value="608" literal="49-1011"/>
    <eLiterals name="_492011" value="609" literal="49-2011"/>
    <eLiterals name="_492021" value="610" literal="49-2021"/>
    <eLiterals name="_492022" value="611" literal="49-2022"/>
    <eLiterals name="_492091" value="612" literal="49-2091"/>
    <eLiterals name="_492092" value="613" literal="49-2092"/>
    <eLiterals name="_492093" value="614" literal="49-2093"/>
    <eLiterals name="_492094" value="615" literal="49-2094"/>
    <eLiterals name="_492095" value="616" literal="49-2095"/>
    <eLiterals name="_492096" value="617" literal="49-2096"/>
    <eLiterals name="_492097" value="618" literal="49-2097"/>
    <eLiterals name="_492098" value="619" literal="49-2098"/>
    <eLiterals name="_493011" value="620" literal="49-3011"/>
    <eLiterals name="_493021" value="621" literal="49-3021"/>
    <eLiterals name="_493022" value="622" literal="49-3022"/>
    <eLiterals name="_493023" value="623" literal="49-3023"/>
    <eLiterals name="_493031" value="624" literal="49-3031"/>
    <eLiterals name="_493041" value="625" literal="49-3041"/>
    <eLiterals name="_493042" value="626" literal="49-3042"/>
    <eLiterals name="_493043" value="627" literal="49-3043"/>
    <eLiterals name="_493051" value="628" literal="49-3051"/>
    <eLiterals name="_493052" value="629" literal="49-3052"/>
    <eLiterals name="_493053" value="630" literal="49-3053"/>
    <eLiterals name="_493091" value="631" literal="49-3091"/>
    <eLiterals name="_493092" value="632" literal="49-3092"/>
    <eLiterals name="_493093" value="633" literal="49-3093"/>
    <eLiterals name="_499011" value="634" literal="49-9011"/>
    <eLiterals name="_499012" value="635" literal="49-9012"/>
    <eLiterals name="_499021" value="636" literal="49-9021"/>
    <eLiterals name="_499031" value="637" literal="49-9031"/>
    <eLiterals name="_499041" value="638" literal="49-9041"/>
    <eLiterals name="_499043" value="639" literal="49-9043"/>
    <eLiterals name="_499044" value="640" literal="49-9044"/>
    <eLiterals name="_499045" value="641" literal="49-9045"/>
    <eLiterals name="_499051" value="642" literal="49-9051"/>
    <eLiterals name="_499052" value="643" literal="49-9052"/>
    <eLiterals name="_499061" value="644" literal="49-9061"/>
    <eLiterals name="_499062" value="645" literal="49-9062"/>
    <eLiterals name="_499063" value="646" literal="49-9063"/>
    <eLiterals name="_499064" value="647" literal="49-9064"/>
    <eLiterals name="_499069" value="648" literal="49-9069"/>
    <eLiterals name="_499071" value="649" literal="49-9071"/>
    <eLiterals name="_499081" value="650" literal="49-9081"/>
    <eLiterals name="_499091" value="651" literal="49-9091"/>
    <eLiterals name="_499092" value="652" literal="49-9092"/>
    <eLiterals name="_499093" value="653" literal="49-9093"/>
    <eLiterals name="_499094" value="654" literal="49-9094"/>
    <eLiterals name="_499095" value="655" literal="49-9095"/>
    <eLiterals name="_499096" value="656" literal="49-9096"/>
    <eLiterals name="_499097" value="657" literal="49-9097"/>
    <eLiterals name="_499098" value="658" literal="49-9098"/>
    <eLiterals name="_499099" value="659" literal="49-9099"/>
    <eLiterals name="_511011" value="660" literal="51-1011"/>
    <eLiterals name="_512011" value="661" literal="51-2011"/>
    <eLiterals name="_512021" value="662" literal="51-2021"/>
    <eLiterals name="_512022" value="663" literal="51-2022"/>
    <eLiterals name="_512023" value="664" literal="51-2023"/>
    <eLiterals name="_512031" value="665" literal="51-2031"/>
    <eLiterals name="_512041" value="666" literal="51-2041"/>
    <eLiterals name="_512091" value="667" literal="51-2091"/>
    <eLiterals name="_512092" value="668" literal="51-2092"/>
    <eLiterals name="_512093" value="669" literal="51-2093"/>
    <eLiterals name="_512099" value="670" literal="51-2099"/>
    <eLiterals name="_513011" value="671" literal="51-3011"/>
    <eLiterals name="_513021" value="672" literal="51-3021"/>
    <eLiterals name="_513022" value="673" literal="51-3022"/>
    <eLiterals name="_513023" value="674" literal="51-3023"/>
    <eLiterals name="_513091" value="675" literal="51-3091"/>
    <eLiterals name="_513092" value="676" literal="51-3092"/>
    <eLiterals name="_513093" value="677" literal="51-3093"/>
    <eLiterals name="_513099" value="678" literal="51-3099"/>
    <eLiterals name="_514011" value="679" literal="51-4011"/>
    <eLiterals name="_514012" value="680" literal="51-4012"/>
    <eLiterals name="_514021" value="681" literal="51-4021"/>
    <eLiterals name="_514022" value="682" literal="51-4022"/>
    <eLiterals name="_514023" value="683" literal="51-4023"/>
    <eLiterals name="_514031" value="684" literal="51-4031"/>
    <eLiterals name="_514032" value="685" literal="51-4032"/>
    <eLiterals name="_514033" value="686" literal="51-4033"/>
    <eLiterals name="_514034" value="687" literal="51-4034"/>
    <eLiterals name="_514035" value="688" literal="51-4035"/>
    <eLiterals name="_514041" value="689" literal="51-4041"/>
    <eLiterals name="_514051" value="690" literal="51-4051"/>
    <eLiterals name="_514052" value="691" literal="51-4052"/>
    <eLiterals name="_514061" value="692" literal="51-4061"/>
    <eLiterals name="_514062" value="693" literal="51-4062"/>
    <eLiterals name="_514071" value="694" literal="51-4071"/>
    <eLiterals name="_514072" value="695" literal="51-4072"/>
    <eLiterals name="_514081" value="696" literal="51-4081"/>
    <eLiterals name="_514111" value="697" literal="51-4111"/>
    <eLiterals name="_514121" value="698" literal="51-4121"/>
    <eLiterals name="_514122" value="699" literal="51-4122"/>
    <eLiterals name="_514191" value="700" literal="51-4191"/>
    <eLiterals name="_514192" value="701" literal="51-4192"/>
    <eLiterals name="_514193" value="702" literal="51-4193"/>
    <eLiterals name="_514194" value="703" literal="51-4194"/>
    <eLiterals name="_514199" value="704" literal="51-4199"/>
    <eLiterals name="_515111" value="705" literal="51-5111"/>
    <eLiterals name="_515112" value="706" literal="51-5112"/>
    <eLiterals name="_515113" value="707" literal="51-5113"/>
    <eLiterals name="_516011" value="708" literal="51-6011"/>
    <eLiterals name="_516021" value="709" literal="51-6021"/>
    <eLiterals name="_516031" value="710" literal="51-6031"/>
    <eLiterals name="_516041" value="711" literal="51-6041"/>
    <eLiterals name="_516042" value="712" literal="51-6042"/>
    <eLiterals name="_516051" value="713" literal="51-6051"/>
    <eLiterals name="_516052" value="714" literal="51-6052"/>
    <eLiterals name="_516061" value="715" literal="51-6061"/>
    <eLiterals name="_516062" value="716" literal="51-6062"/>
    <eLiterals name="_516063" value="717" literal="51-6063"/>
    <eLiterals name="_516064" value="718" literal="51-6064"/>
    <eLiterals name="_516091" value="719" literal="51-6091"/>
    <eLiterals name="_516092" value="720" literal="51-6092"/>
    <eLiterals name="_516093" value="721" literal="51-6093"/>
    <eLiterals name="_516099" value="722" literal="51-6099"/>
    <eLiterals name="_517011" value="723" literal="51-7011"/>
    <eLiterals name="_517021" value="724" literal="51-7021"/>
    <eLiterals name="_517031" value="725" literal="51-7031"/>
    <eLiterals name="_517032" value="726" literal="51-7032"/>
    <eLiterals name="_517041" value="727" literal="51-7041"/>
    <eLiterals name="_517042" value="728" literal="51-7042"/>
    <eLiterals name="_517099" value="729" literal="51-7099"/>
    <eLiterals name="_518011" value="730" literal="51-8011"/>
    <eLiterals name="_518012" value="731" literal="51-8012"/>
    <eLiterals name="_518013" value="732" literal="51-8013"/>
    <eLiterals name="_518021" value="733" literal="51-8021"/>
    <eLiterals name="_518031" value="734" literal="51-8031"/>
    <eLiterals name="_518091" value="735" literal="51-8091"/>
    <eLiterals name="_518092" value="736" literal="51-8092"/>
    <eLiterals name="_518093" value="737" literal="51-8093"/>
    <eLiterals name="_518099" value="738" literal="51-8099"/>
    <eLiterals name="_519011" value="739" literal="51-9011"/>
    <eLiterals name="_519012" value="740" literal="51-9012"/>
    <eLiterals name="_519021" value="741" literal="51-9021"/>
    <eLiterals name="_519022" value="742" literal="51-9022"/>
    <eLiterals name="_519023" value="743" literal="51-9023"/>
    <eLiterals name="_519031" value="744" literal="51-9031"/>
    <eLiterals name="_519032" value="745" literal="51-9032"/>
    <eLiterals name="_519041" value="746" literal="51-9041"/>
    <eLiterals name="_519051" value="747" literal="51-9051"/>
    <eLiterals name="_519061" value="748" literal="51-9061"/>
    <eLiterals name="_519071" value="749" literal="51-9071"/>
    <eLiterals name="_519081" value="750" literal="51-9081"/>
    <eLiterals name="_519082" value="751" literal="51-9082"/>
    <eLiterals name="_519083" value="752" literal="51-9083"/>
    <eLiterals name="_519111" value="753" literal="51-9111"/>
    <eLiterals name="_519121" value="754" literal="51-9121"/>
    <eLiterals name="_519122" value="755" literal="51-9122"/>
    <eLiterals name="_519123" value="756" literal="51-9123"/>
    <eLiterals name="_519141" value="757" literal="51-9141"/>
    <eLiterals name="_519151" value="758" literal="51-9151"/>
    <eLiterals name="_519191" value="759" literal="51-9191"/>
    <eLiterals name="_519192" value="760" literal="51-9192"/>
    <eLiterals name="_519193" value="761" literal="51-9193"/>
    <eLiterals name="_519194" value="762" literal="51-9194"/>
    <eLiterals name="_519195" value="763" literal="51-9195"/>
    <eLiterals name="_519196" value="764" literal="51-9196"/>
    <eLiterals name="_519197" value="765" literal="51-9197"/>
    <eLiterals name="_519198" value="766" literal="51-9198"/>
    <eLiterals name="_519199" value="767" literal="51-9199"/>
    <eLiterals name="_531011" value="768" literal="53-1011"/>
    <eLiterals name="_531021" value="769" literal="53-1021"/>
    <eLiterals name="_531031" value="770" literal="53-1031"/>
    <eLiterals name="_532011" value="771" literal="53-2011"/>
    <eLiterals name="_532012" value="772" literal="53-2012"/>
    <eLiterals name="_532021" value="773" literal="53-2021"/>
    <eLiterals name="_532022" value="774" literal="53-2022"/>
    <eLiterals name="_532031" value="775" literal="53-2031"/>
    <eLiterals name="_533011" value="776" literal="53-3011"/>
    <eLiterals name="_533021" value="777" literal="53-3021"/>
    <eLiterals name="_533022" value="778" literal="53-3022"/>
    <eLiterals name="_533031" value="779" literal="53-3031"/>
    <eLiterals name="_533032" value="780" literal="53-3032"/>
    <eLiterals name="_533033" value="781" literal="53-3033"/>
    <eLiterals name="_533041" value="782" literal="53-3041"/>
    <eLiterals name="_533099" value="783" literal="53-3099"/>
    <eLiterals name="_534011" value="784" literal="53-4011"/>
    <eLiterals name="_534012" value="785" literal="53-4012"/>
    <eLiterals name="_534013" value="786" literal="53-4013"/>
    <eLiterals name="_534021" value="787" literal="53-4021"/>
    <eLiterals name="_534031" value="788" literal="53-4031"/>
    <eLiterals name="_534041" value="789" literal="53-4041"/>
    <eLiterals name="_534099" value="790" literal="53-4099"/>
    <eLiterals name="_535011" value="791" literal="53-5011"/>
    <eLiterals name="_535021" value="792" literal="53-5021"/>
    <eLiterals name="_535022" value="793" literal="53-5022"/>
    <eLiterals name="_535031" value="794" literal="53-5031"/>
    <eLiterals name="_536011" value="795" literal="53-6011"/>
    <eLiterals name="_536021" value="796" literal="53-6021"/>
    <eLiterals name="_536031" value="797" literal="53-6031"/>
    <eLiterals name="_536041" value="798" literal="53-6041"/>
    <eLiterals name="_536051" value="799" literal="53-6051"/>
    <eLiterals name="_536061" value="800" literal="53-6061"/>
    <eLiterals name="_536099" value="801" literal="53-6099"/>
    <eLiterals name="_537011" value="802" literal="53-7011"/>
    <eLiterals name="_537021" value="803" literal="53-7021"/>
    <eLiterals name="_537031" value="804" literal="53-7031"/>
    <eLiterals name="_537032" value="805" literal="53-7032"/>
    <eLiterals name="_537033" value="806" literal="53-7033"/>
    <eLiterals name="_537041" value="807" literal="53-7041"/>
    <eLiterals name="_537051" value="808" literal="53-7051"/>
    <eLiterals name="_537061" value="809" literal="53-7061"/>
    <eLiterals name="_537062" value="810" literal="53-7062"/>
    <eLiterals name="_537063" value="811" literal="53-7063"/>
    <eLiterals name="_537064" value="812" literal="53-7064"/>
    <eLiterals name="_537071" value="813" literal="53-7071"/>
    <eLiterals name="_537072" value="814" literal="53-7072"/>
    <eLiterals name="_537073" value="815" literal="53-7073"/>
    <eLiterals name="_537081" value="816" literal="53-7081"/>
    <eLiterals name="_537111" value="817" literal="53-7111"/>
    <eLiterals name="_537121" value="818" literal="53-7121"/>
    <eLiterals name="_537199" value="819" literal="53-7199"/>
    <eLiterals name="_551011" value="820" literal="55-1011"/>
    <eLiterals name="_551012" value="821" literal="55-1012"/>
    <eLiterals name="_551013" value="822" literal="55-1013"/>
    <eLiterals name="_551014" value="823" literal="55-1014"/>
    <eLiterals name="_551015" value="824" literal="55-1015"/>
    <eLiterals name="_551016" value="825" literal="55-1016"/>
    <eLiterals name="_551017" value="826" literal="55-1017"/>
    <eLiterals name="_551019" value="827" literal="55-1019"/>
    <eLiterals name="_552011" value="828" literal="55-2011"/>
    <eLiterals name="_552012" value="829" literal="55-2012"/>
    <eLiterals name="_552013" value="830" literal="55-2013"/>
    <eLiterals name="_553011" value="831" literal="55-3011"/>
    <eLiterals name="_553012" value="832" literal="55-3012"/>
    <eLiterals name="_553013" value="833" literal="55-3013"/>
    <eLiterals name="_553014" value="834" literal="55-3014"/>
    <eLiterals name="_553015" value="835" literal="55-3015"/>
    <eLiterals name="_553016" value="836" literal="55-3016"/>
    <eLiterals name="_553017" value="837" literal="55-3017"/>
    <eLiterals name="_553018" value="838" literal="55-3018"/>
    <eLiterals name="_553019" value="839" literal="55-3019"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OccupationCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="OccupationCodeSimpleType:Object"/>
      <details key="baseType" value="OccupationCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupationCodeType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="OccupationCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//OccupationCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
