/*
* generated by Xtext
*/
package org.w3;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Xpath20UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.w3.ui.internal.Xpath20Activator.getInstance().getInjector("org.w3.Xpath20");
	}
	
}
