/*
 * generated by Xtext
 */
package org.w3;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Xpath20RuntimeModule extends org.w3.AbstractXpath20RuntimeModule {

}
