/*
* generated by Xtext
*/
package org.w3;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Xpath20StandaloneSetup extends Xpath20StandaloneSetupGenerated{

	public static void doSetup() {
		new Xpath20StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

